'use server'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

function normalize(value:string){return value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function parseJson(value:FormDataEntryValue|null){try{return JSON.parse(String(value||'[]'))}catch{return[]}}
function cleanChapters(value:any){const seen=new Set<string>();const out:any[]=[];for(const item of Array.isArray(value)?value:[]){const raw=item?.number,number=raw===null||raw===''?null:Number(raw),title=String(item?.title||'').trim();if(number!==null&&(!Number.isInteger(number)||number<1))continue;if(number===null&&!title)continue;const key=`${number??''}|${title.toLowerCase()}`;if(!seen.has(key)){seen.add(key);out.push({number,title})}}return out}
function cleanSubjects(value:any){const seen=new Set<string>();return(Array.isArray(value)?value:[]).map(x=>String(x).trim()).filter(x=>{const key=x.toLowerCase();if(!x||seen.has(key))return false;seen.add(key);return true})}
async function persistQuestionTags(supabase:any,userId:string,questions:any[]){const tagged=questions.filter(q=>q&&String(q.prompt||'').trim()&&(q.chapters?.length||q.subjects?.length));if(!tagged.length)return;const prompts=[...new Set(tagged.map(q=>String(q.prompt).trim()))],{data:bank}=await supabase.from('question_bank').select('id,prompt').eq('teacher_id',userId).in('prompt',prompts);if(!bank?.length)return;const byPrompt=new Map(bank.map((row:any)=>[normalize(row.prompt),row.id])),ids=bank.map((row:any)=>row.id);const[{data:chapterRows},{data:subjectRows}]=await Promise.all([supabase.from('question_bank_chapters').select('question_id,chapter_number,chapter_title').in('question_id',ids),supabase.from('question_bank_subjects').select('question_id,subject_category').in('question_id',ids)]);const chapterKeys=new Set((chapterRows??[]).map((row:any)=>`${row.question_id}|${row.chapter_number??''}|${String(row.chapter_title||'').trim().toLowerCase()}`)),subjectKeys=new Set((subjectRows??[]).map((row:any)=>`${row.question_id}|${String(row.subject_category||'').trim().toLowerCase()}`)),chapters:any[]=[],subjects:any[]=[];for(const q of tagged){const questionId=byPrompt.get(normalize(String(q.prompt)));if(!questionId)continue;for(const raw of q.chapters??[]){const number=raw?.number===null||raw?.number===''?null:Number(raw?.number),title=String(raw?.title||'').trim();if(number===null&&!title)continue;if(number!==null&&(!Number.isInteger(number)||number<1))continue;const key=`${questionId}|${number??''}|${title.toLowerCase()}`;if(!chapterKeys.has(key)){chapterKeys.add(key);chapters.push({question_id:questionId,teacher_id:userId,chapter_number:number,chapter_title:title||null})}}for(const raw of q.subjects??[]){const subject=String(raw||'').trim();if(!subject)continue;const key=`${questionId}|${subject.toLowerCase()}`;if(!subjectKeys.has(key)){subjectKeys.add(key);subjects.push({question_id:questionId,teacher_id:userId,subject_category:subject})}}}if(chapters.length)await supabase.from('question_bank_chapters').insert(chapters);if(subjects.length)await supabase.from('question_bank_subjects').insert(subjects)}

export async function saveTestEdit(testId:string,fd:FormData){
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
  const{data:profile}=await supabase.from('profiles').select('role,teacher_approved').eq('id',user.id).single();if(profile?.role!=='teacher'||!profile.teacher_approved)redirect('/dashboard')
  const{data:test}=await supabase.from('tests').select('id,teacher_id,title,questions_per_attempt,require_focused_retake_before_full,focused_retake_percent,focused_retake_min_score,focused_retake_hints,unlimited_attempts_until_due,max_attempts,due_at').eq('id',testId).single();if(!test||test.teacher_id!==user.id)redirect('/dashboard')
  const title=String(fd.get('title')||'').trim(),description=String(fd.get('description')||''),randomize=fd.get('randomize')==='on',duration=Number(fd.get('duration_minutes')||0),singlePage=fd.get('single_page')==='on',passingScore=Number(fd.get('passing_score')||70),examPreset=String(fd.get('exam_preset')||'custom'),assessmentType=String(fd.get('assessment_type')||'custom'),chapterLabel=String(fd.get('chapter_label')||'')
  const questionCount=Number(fd.get('question_count')||0);const questions=[] as any[]
  for(let qi=0;qi<questionCount;qi++){
    const choices=fd.getAll(`q_${qi}_choices`).map(x=>String(x).trim()).filter(Boolean),chapters=cleanChapters(parseJson(fd.get(`q_${qi}_chapters_json`))),subjects=cleanSubjects(parseJson(fd.get(`q_${qi}_subjects_json`)));const firstChapter=chapters[0],firstSubject=subjects[0]||String(fd.get(`q_${qi}_subject`)||'').trim()
    questions.push({prompt:String(fd.get(`q_${qi}_prompt`)||'').trim(),choices,correctIndex:Number(fd.get(`q_${qi}_correct`)||0),contentArea:firstSubject,subjectCategory:firstSubject,chapterNumber:firstChapter?.number??(String(fd.get(`q_${qi}_chapter_number`)||'').trim()?Number(fd.get(`q_${qi}_chapter_number`)):null),chapterTitle:firstChapter?.title??String(fd.get(`q_${qi}_chapter_title`)||'').trim(),focusedRetakeHint:String(fd.get(`q_${qi}_hint`)||'').trim(),explanation:String(fd.get(`q_${qi}_explanation`)||'').trim(),sourceType:'teacher',chapters,subjects})
  }
  const{count}=await supabase.from('attempts').select('*',{count:'exact',head:true}).eq('test_id',testId).not('submitted_at','is',null)
  if((count??0)>0){const revisedTitle=title===test.title?`${title} — Revised`:title,dueAt=test.due_at&&new Date(test.due_at).getTime()>Date.now()?test.due_at:null;const{data:newId,error}=await supabase.rpc('create_test_with_questions_v6',{p_title:revisedTitle,p_description:description,p_randomize:randomize,p_duration_minutes:duration,p_one_question_per_page:singlePage,p_passing_score:passingScore,p_exam_preset:examPreset,p_assessment_type:assessmentType,p_chapter_label:chapterLabel,p_questions:questions,p_questions_per_attempt:Math.min(Number(test.questions_per_attempt)||questions.length,questions.length),p_require_focused_retake_before_full:Boolean(test.require_focused_retake_before_full),p_focused_retake_percent:Number(test.focused_retake_percent)||50,p_focused_retake_min_score:Number(test.focused_retake_min_score)||0,p_focused_retake_hints:test.focused_retake_hints!==false,p_unlimited_attempts_until_due:Boolean(test.unlimited_attempts_until_due)&&Boolean(dueAt),p_max_attempts:Number(test.max_attempts)||1,p_due_at:dueAt});if(error)redirect(`/tests/${testId}/edit?error=${encodeURIComponent(error.message)}`);await persistQuestionTags(supabase,user.id,questions);redirect(`/tests/${newId}/edit?message=${encodeURIComponent('A revised draft was created so the original student reports stay intact.')}`)}
  const{error}=await supabase.rpc('update_test_with_questions_v2',{p_test_id:testId,p_title:title,p_description:description,p_randomize:randomize,p_duration_minutes:duration,p_one_question_per_page:singlePage,p_passing_score:passingScore,p_exam_preset:examPreset,p_assessment_type:assessmentType,p_chapter_label:chapterLabel,p_questions:questions});if(error)redirect(`/tests/${testId}/edit?error=${encodeURIComponent(error.message)}`);await persistQuestionTags(supabase,user.id,questions);redirect(`/tests/${testId}/edit?message=${encodeURIComponent('Test updated.')}`)
}
