import Link from 'next/link'
import {notFound,redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import {saveTestEdit} from './actions'

export default async function EditTest({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string,message?:string}>}){
 const{id}=await params;const q=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const{data:profile}=await supabase.from('profiles').select('role,teacher_approved').eq('id',user.id).single();if(profile?.role!=='teacher'||!profile.teacher_approved)redirect('/dashboard')
 const{data:test}=await supabase.from('tests').select('id,teacher_id,title,description,randomize_questions,duration_minutes,one_question_per_page,passing_score_percent,exam_preset,assessment_type,chapter_label').eq('id',id).single();if(!test||test.teacher_id!==user.id)notFound()
 const{data:questions}=await supabase.from('questions').select('id,prompt,position,content_area').eq('test_id',id).order('position');const qIds=(questions??[]).map((x:any)=>x.id)
 const{data:choices}=qIds.length?await supabase.from('choices').select('id,question_id,label,position').in('question_id',qIds).order('position'):{data:[] as any[]};const{data:answers}=qIds.length?await supabase.from('question_answers').select('question_id,choice_id').in('question_id',qIds):{data:[] as any[]};const answerMap=new Map((answers??[]).map((a:any)=>[a.question_id,a.choice_id]))
 const{count:submitted}=await supabase.from('attempts').select('*',{count:'exact',head:true}).eq('test_id',id).not('submitted_at','is',null)
 return <main><Link href="/dashboard">← Test library</Link><div className="row between"><div><h1>Edit test</h1><p className="muted">Update the title, settings, questions, choices, and correct answers.</p></div><Link className="secondary button" href={`/tests/${id}/preview`}>Student view</Link></div>{q.error&&<p className="bad notice">{q.error}</p>}{q.message&&<p className="good notice">{q.message}</p>}{(submitted??0)>0&&<div className="notice"><b>Student history protected</b><p className="muted">This test already has submitted attempts. Saving content changes will create a revised draft instead of altering the version tied to those reports.</p></div>}
 <form action={saveTestEdit.bind(null,id)} className="stack"><section className="card"><label>Test title</label><input name="title" required defaultValue={test.title}/><label>Description</label><textarea name="description" rows={3} defaultValue={test.description??''}/><input type="hidden" name="assessment_type" value={test.assessment_type??'custom'}/><input type="hidden" name="exam_preset" value={test.exam_preset??'custom'}/><label>Chapter / topic</label><input name="chapter_label" defaultValue={test.chapter_label??''}/><div className="settings-grid"><div><label>Timer (minutes)</label><input name="duration_minutes" type="number" min="0" max="600" defaultValue={test.duration_minutes}/></div><div><label>Passing score (%)</label><input name="passing_score" type="number" min="0" max="100" defaultValue={test.passing_score_percent}/></div></div><label className="check"><input name="single_page" type="checkbox" defaultChecked={test.one_question_per_page}/> Show one question per page</label><label className="check"><input name="randomize" type="checkbox" defaultChecked={test.randomize_questions}/> Randomize question order</label></section>
 <input type="hidden" name="question_count" value={(questions??[]).length}/>{(questions??[]).map((question:any,qi:number)=>{const qc=(choices??[]).filter((c:any)=>c.question_id===question.id).sort((a:any,b:any)=>a.position-b.position);const correctId=answerMap.get(question.id);const correct=Math.max(0,qc.findIndex((c:any)=>c.id===correctId));return <section className="card" key={question.id}><h2>Question {qi+1}</h2><label>Content area / topic</label><input name={`q_${qi}_area`} defaultValue={question.content_area??''}/><label>Question</label><textarea name={`q_${qi}_prompt`} rows={3} required defaultValue={question.prompt}/><input type="hidden" name={`q_${qi}_choice_count`} value={qc.length}/><p className="muted">Select the correct answer, then edit any choice text.</p>{qc.map((choice:any,ci:number)=><div className="choice-editor" key={choice.id}><input type="radio" name={`q_${qi}_correct`} value={ci} defaultChecked={ci===correct}/><input name={`q_${qi}_choice_${ci}`} required defaultValue={choice.label}/></div>)}</section>})}<div className="row"><button>Save changes</button><Link className="secondary button" href="/dashboard">Cancel</Link></div></form></main>
}
