import Link from 'next/link'
import {notFound,redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import QuestionEditorFields,{ChapterOption,QuestionEditorValue} from '@/components/QuestionEditorFields'
import {saveTestEdit} from './actions'

function normalize(value:string){return value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}

export default async function EditTest({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string,message?:string}>}){
 const{id}=await params;const q=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const{data:profile}=await supabase.from('profiles').select('role,teacher_approved').eq('id',user.id).single();if(profile?.role!=='teacher'||!profile.teacher_approved)redirect('/dashboard')
 const{data:test}=await supabase.from('tests').select('id,teacher_id,title,description,randomize_questions,duration_minutes,one_question_per_page,passing_score_percent,exam_preset,assessment_type,chapter_label').eq('id',id).single();if(!test||test.teacher_id!==user.id)notFound()
 const{data:questions}=await supabase.from('questions').select('id,prompt,position,content_area,subject_category,chapter_number,chapter_title,focused_retake_hint').eq('test_id',id).order('position');const qIds=(questions??[]).map((x:any)=>x.id)
 const[{data:choices},{data:answers},{data:bankMeta},{data:chapterRows},{data:subjectRows}]=await Promise.all([
  qIds.length?supabase.from('choices').select('id,question_id,label,position').in('question_id',qIds).order('position'):Promise.resolve({data:[] as any[]}),
  qIds.length?supabase.from('question_answers').select('question_id,choice_id').in('question_id',qIds):Promise.resolve({data:[] as any[]}),
  supabase.from('question_bank').select('id,prompt,chapter_number,chapter_title,subject_category,content_area,explanation').eq('teacher_id',user.id).limit(2000),
  supabase.from('question_bank_chapters').select('question_id,chapter_number,chapter_title').eq('teacher_id',user.id).limit(10000),
  supabase.from('question_bank_subjects').select('question_id,subject_category').eq('teacher_id',user.id).limit(10000)
 ])
 const chaptersByBank=new Map<string,ChapterOption[]>();for(const row of chapterRows??[]){const item=row as any;chaptersByBank.set(item.question_id,[...(chaptersByBank.get(item.question_id)||[]),{number:item.chapter_number??null,title:item.chapter_title??''}])}
 const subjectsByBank=new Map<string,string[]>();for(const row of subjectRows??[]){const item=row as any;subjectsByBank.set(item.question_id,[...(subjectsByBank.get(item.question_id)||[]),String(item.subject_category||'').trim()].filter(Boolean))}
 const answerMap=new Map((answers??[]).map((a:any)=>[a.question_id,a.choice_id])),bankMap=new Map((bankMeta??[]).map((item:any)=>[normalize(item.prompt),{...item,chapters:chaptersByBank.get(item.id)||[],subjects:subjectsByBank.get(item.id)||[]}]))
 const chapters=[...new Map((chapterRows??[]).map((item:any)=>{const option:ChapterOption={number:item.chapter_number??null,title:item.chapter_title??''};return[`${option.number??''}|${option.title.toLowerCase()}`,option]})).values()]
 const subjects=[...new Set((subjectRows??[]).map((item:any)=>String(item.subject_category||'').trim()).filter(Boolean))]
 const{count:submitted}=await supabase.from('attempts').select('*',{count:'exact',head:true}).eq('test_id',id).not('submitted_at','is',null)
 return <main><Link href="/dashboard">← Test library</Link><div className="row between"><div><h1>Edit test</h1><p className="muted">The same multi-classification question editor is used here and in your Question Bank.</p></div><Link className="secondary button" href={`/tests/${id}/preview`}>Student view</Link></div>{q.error&&<p className="bad notice">{q.error}</p>}{q.message&&<p className="good notice">{q.message}</p>}{(submitted??0)>0&&<div className="notice"><b>Student history protected</b><p className="muted">This test already has submitted attempts. Saving content changes will create a revised draft instead of altering the version tied to those reports.</p></div>}
 <form action={saveTestEdit.bind(null,id)} className="stack"><section className="card"><label>Test title</label><input name="title" required defaultValue={test.title}/><label>Description</label><textarea name="description" rows={3} defaultValue={test.description??''}/><input type="hidden" name="assessment_type" value={test.assessment_type??'custom'}/><input type="hidden" name="exam_preset" value={test.exam_preset??'custom'}/><label>Chapter / topic</label><input name="chapter_label" defaultValue={test.chapter_label??''}/><div className="settings-grid"><div><label>Timer (minutes)</label><input name="duration_minutes" type="number" min="0" max="600" defaultValue={test.duration_minutes}/></div><div><label>Passing score (%)</label><input name="passing_score" type="number" min="0" max="100" defaultValue={test.passing_score_percent}/></div></div><label className="check"><input name="single_page" type="checkbox" defaultChecked={test.one_question_per_page}/> Show one question per page</label><label className="check"><input name="randomize" type="checkbox" defaultChecked={test.randomize_questions}/> Randomize question order</label></section>
 <input type="hidden" name="question_count" value={(questions??[]).length}/>{(questions??[]).map((question:any,qi:number)=>{const qc=(choices??[]).filter((c:any)=>c.question_id===question.id).sort((a:any,b:any)=>a.position-b.position),correctId=answerMap.get(question.id),correct=Math.max(0,qc.findIndex((c:any)=>c.id===correctId)),bank=bankMap.get(normalize(question.prompt)) as any;const value:QuestionEditorValue={prompt:question.prompt,choices:qc.map((c:any)=>c.label),correctIndex:correct,chapterNumber:question.chapter_number??bank?.chapter_number??null,chapterTitle:question.chapter_title??bank?.chapter_title??'',subjectCategory:question.subject_category??question.content_area??bank?.subject_category??bank?.content_area??'',focusedRetakeHint:question.focused_retake_hint??'',explanation:bank?.explanation??'',sourceType:'teacher',chapters:bank?.chapters?.length?bank.chapters:undefined,subjects:bank?.subjects?.length?bank.subjects:undefined};return <section className="card" key={question.id}><QuestionEditorFields title={`Question ${qi+1}`} value={value} chapterOptions={chapters as ChapterOption[]} subjectOptions={subjects} names={{prompt:`q_${qi}_prompt`,chapterNumber:`q_${qi}_chapter_number`,chapterTitle:`q_${qi}_chapter_title`,subjectCategory:`q_${qi}_subject`,chaptersJson:`q_${qi}_chapters_json`,subjectsJson:`q_${qi}_subjects_json`,choices:`q_${qi}_choices`,correctIndex:`q_${qi}_correct`,focusedRetakeHint:`q_${qi}_hint`,explanation:`q_${qi}_explanation`}}/></section>})}<div className="row"><button>Save changes</button><Link className="secondary button" href="/dashboard">Cancel</Link></div></form></main>
}
