'use client'

import {ChangeEvent,useMemo,useState} from 'react'

type ChapterTag={number:number|null;title:string}
type ExistingQuestion={id:string;prompt:string;choices:string[];correct_index:number;chapters:ChapterTag[];subjects:string[]}
type Resolution='new'|'merge'|'skip'|'review'
type StageRow={id:string;prompt:string;choices:string[];correctIndex:number;chapters:ChapterTag[];subjects:string[];explanation:string;focusedHint:string;resolution:Resolution;targetId:string|null;matchKind:'none'|'exact'|'near'|'conflict';similarity:number}

type Props={existing:ExistingQuestion[];chapterOptions:ChapterTag[];subjectOptions:string[];action:(formData:FormData)=>void}
const CHOICE_HEADERS=['choice a','choice b','choice c','choice d','choice e','choice f']
function normalize(value:string){return value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function tokenSimilarity(a:string,b:string){const A=new Set(normalize(a).split(' ').filter(Boolean)),B=new Set(normalize(b).split(' ').filter(Boolean));if(!A.size||!B.size)return 0;let overlap=0;for(const token of A)if(B.has(token))overlap++;return overlap/(A.size+B.size-overlap)}
function sameAnswers(existing:ExistingQuestion,row:{choices:string[];correctIndex:number}){return existing.correct_index===row.correctIndex&&existing.choices.length===row.choices.length&&existing.choices.every((choice,i)=>choice.trim()===row.choices[i]?.trim())}
function chapterLabel(tag:ChapterTag){if(tag.number)return `Chapter ${tag.number}${tag.title?` — ${tag.title}`:''}`;return tag.title}
function parseChapter(value:string):ChapterTag|null{const text=value.trim();if(!text)return null;const match=text.match(/^chapter\s+(\d+)(?:\s*[—–-]\s*(.*))?$/i);if(match)return{number:Number(match[1]),title:(match[2]||'').trim()};if(/^\d+$/.test(text))return{number:Number(text),title:''};return{number:null,title:text}}
function dedupeChapters(items:ChapterTag[]){const seen=new Set<string>();return items.filter(item=>{const key=`${item.number??''}|${item.title.trim().toLowerCase()}`;if((item.number===null&&!item.title.trim())||seen.has(key))return false;seen.add(key);return true})}
function dedupeSubjects(items:string[]){const seen=new Set<string>();return items.map(x=>x.trim()).filter(x=>{const key=x.toLowerCase();if(!x||seen.has(key))return false;seen.add(key);return true})}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}
function parseRows(text:string){const table=parseCsv(text);if(table.length<2)return{rows:[] as Omit<StageRow,'resolution'|'targetId'|'matchKind'|'similarity'>[],errors:['Include a header row and at least one question row.']};const headers=table[0].map(x=>x.trim().toLowerCase()),idx=(name:string)=>headers.indexOf(name);const questionCol=idx('question'),correctCol=idx('correct answer'),chapterNumberCol=idx('chapter number'),chapterTitleCol=idx('chapter title'),subjectCol=idx('subject category'),contentAreaCol=idx('content area'),explanationCol=idx('explanation'),hintCol=idx('focused retake hint'),choiceCols=CHOICE_HEADERS.map(idx),errors:string[]=[];if(questionCol<0)errors.push('Missing Question column.');if(correctCol<0)errors.push('Missing Correct Answer column.');if(choiceCols[0]<0||choiceCols[1]<0)errors.push('Choice A and Choice B are required.');if(errors.length)return{rows:[],errors};const parsed:Omit<StageRow,'resolution'|'targetId'|'matchKind'|'similarity'>[]=[];table.slice(1).forEach((raw,rowIndex)=>{const prompt=String(raw[questionCol]||'').trim();if(!prompt)return;const rawChoices=choiceCols.map(col=>col>=0?String(raw[col]||'').trim():'');const choices=rawChoices.filter(Boolean);if(choices.length<2){errors.push(`Row ${rowIndex+2}: at least two answer choices are required.`);return}const answer=String(raw[correctCol]||'').trim();let rawCorrect=-1;if(/^[A-F]$/i.test(answer))rawCorrect=answer.toUpperCase().charCodeAt(0)-65;else if(/^[1-6]$/.test(answer))rawCorrect=Number(answer)-1;else rawCorrect=rawChoices.findIndex(choice=>choice.toLowerCase()===answer.toLowerCase());if(rawCorrect<0||!rawChoices[rawCorrect]){errors.push(`Row ${rowIndex+2}: Correct Answer does not match a choice.`);return}const correctIndex=rawChoices.slice(0,rawCorrect).filter(Boolean).length;const numberRaw=chapterNumberCol>=0?String(raw[chapterNumberCol]||'').trim():'';const number=numberRaw&&/^\d+$/.test(numberRaw)?Number(numberRaw):null;const title=chapterTitleCol>=0?String(raw[chapterTitleCol]||'').trim():'';const chapters=number||title?[{number,title}]:[];const subject=(subjectCol>=0?String(raw[subjectCol]||'').trim():'')||(contentAreaCol>=0?String(raw[contentAreaCol]||'').trim():'');parsed.push({id:`row-${rowIndex}-${normalize(prompt).slice(0,24)}`,prompt,choices,correctIndex,chapters,subjects:subject?[subject]:[],explanation:explanationCol>=0?String(raw[explanationCol]||'').trim():'',focusedHint:hintCol>=0?String(raw[hintCol]||'').trim():''})});return{rows:parsed,errors}}

function TagAdder({kind,options,onAdd}:{kind:'chapter'|'subject';options:string[];onAdd:(value:string)=>void}){const[value,setValue]=useState('');return <div className="import-tag-adder"><input value={value} onChange={e=>setValue(e.target.value)} list={`import-${kind}-options`} placeholder={kind==='chapter'?'Add chapter':'Add subject'}/><button className="secondary" type="button" onClick={()=>{if(value.trim()){onAdd(value);setValue('')}}}>Add</button><datalist id={`import-${kind}-options`}>{options.map(option=><option value={option} key={option}/>)}</datalist></div>}

export default function ImportStager({existing,chapterOptions,subjectOptions,action}:Props){
 const[rows,setRows]=useState<StageRow[]>([]),[errors,setErrors]=useState<string[]>([]),[paste,setPaste]=useState(''),[globalChapter,setGlobalChapter]=useState(''),[globalSubject,setGlobalSubject]=useState('')
 const chapterLabels=useMemo(()=>chapterOptions.map(chapterLabel).filter(Boolean),[chapterOptions])
 const existingByNormalized=useMemo(()=>new Map(existing.map(q=>[normalize(q.prompt),q])),[existing])
 function classify(parsed:ReturnType<typeof parseRows>['rows']){const staged:StageRow[]=parsed.map(row=>{const exact=existingByNormalized.get(normalize(row.prompt));if(exact){const same=sameAnswers(exact,row);return{...row,resolution:same?'merge':'skip',targetId:exact.id,matchKind:same?'exact':'conflict',similarity:1}}let best:ExistingQuestion|undefined,bestScore=0;for(const candidate of existing){const score=tokenSimilarity(row.prompt,candidate.prompt);if(score>bestScore){best=candidate;bestScore=score}}if(best&&bestScore>=.72)return{...row,resolution:'review',targetId:best.id,matchKind:'near',similarity:bestScore};return{...row,resolution:'new',targetId:null,matchKind:'none',similarity:0}});const seen=new Map<string,number>();for(let i=0;i<staged.length;i++){const key=normalize(staged[i].prompt),prior=seen.get(key);if(prior!==undefined){staged[i]={...staged[i],resolution:'skip',matchKind:'conflict',targetId:null,similarity:1};errors.push(`Import rows ${prior+2} and ${i+2} repeat the same question. Only the first staged copy can be imported.`)}else seen.set(key,i)}setRows(staged)}
 function stageText(text:string){const result=parseRows(text);setErrors([...result.errors]);classify(result.rows)}
 async function fileChanged(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!file.name.toLowerCase().endsWith('.csv')){setErrors(['Upload a CSV file for this importer.']);return}stageText(await file.text());event.target.value=''}
 function patchRow(id:string,patch:Partial<StageRow>){setRows(current=>current.map(row=>row.id===id?{...row,...patch}:row))}
 function addChapter(id:string,value:string){const tag=parseChapter(value);if(tag)patchRow(id,{chapters:dedupeChapters([...(rows.find(r=>r.id===id)?.chapters||[]),tag])})}
 function addSubject(id:string,value:string){patchRow(id,{subjects:dedupeSubjects([...(rows.find(r=>r.id===id)?.subjects||[]),value])})}
 function applyBulk(){const chapter=parseChapter(globalChapter),subject=globalSubject.trim();setRows(current=>current.map(row=>({...row,chapters:chapter?dedupeChapters([...row.chapters,chapter]):row.chapters,subjects:subject?dedupeSubjects([...row.subjects,subject]):row.subjects})));setGlobalChapter('');setGlobalSubject('')}
 const reviewCount=rows.filter(row=>row.resolution==='review').length,importCount=rows.filter(row=>row.resolution==='new').length,mergeCount=rows.filter(row=>row.resolution==='merge').length,skipCount=rows.filter(row=>row.resolution==='skip').length
 const payload=JSON.stringify(rows.map(({id,...row})=>row))
 return <div className="stack import-stager">
  <section className="card"><h2>1. Stage questions</h2><p className="muted">Nothing is saved yet. Upload the CramLoop CSV template or paste CSV-formatted rows below.</p><div className="row" style={{flexWrap:'wrap'}}><label className="button-like" htmlFor="question-import-file">Choose CSV file</label><input id="question-import-file" type="file" accept=".csv,text/csv" onChange={fileChanged} style={{display:'none'}}/><a className="secondary button" href="/templates/question-import-template.csv" download>Download template</a></div><label>Or paste CSV</label><textarea rows={7} value={paste} onChange={e=>setPaste(e.target.value)} placeholder={'Question,Correct Answer,Choice A,Choice B,Chapter Number,Chapter Title,Subject Category\nWhat is...?,A,Answer one,Answer two,2,Safety,Safety & Sanitation'}/><button className="secondary" type="button" onClick={()=>stageText(paste)} disabled={!paste.trim()}>Stage pasted questions</button>{errors.map((error,i)=><p className="bad notice" key={i}>{error}</p>)}</section>
  {rows.length>0&&<><section className="card"><div className="row between" style={{alignItems:'flex-start',gap:12,flexWrap:'wrap'}}><div><h2>2. Review before import</h2><p className="muted">Exact matches can merge classifications. Similar wording needs your decision.</p></div><div className="import-summary"><span className="pill">{rows.length} staged</span><span>{importCount} new · {mergeCount} merge · {skipCount} skip</span>{reviewCount>0&&<b className="bad">{reviewCount} need review</b>}</div></div><div className="import-bulk"><b>Add classifications to every staged row</b><div className="import-bulk-grid"><input value={globalChapter} onChange={e=>setGlobalChapter(e.target.value)} list="import-chapter-options" placeholder="Chapter 8 — Chemical Services"/><input value={globalSubject} onChange={e=>setGlobalSubject(e.target.value)} list="import-subject-options" placeholder="Subject category"/><button className="secondary" type="button" onClick={applyBulk} disabled={!globalChapter.trim()&&!globalSubject.trim()}>Apply to all</button></div><datalist id="import-chapter-options">{chapterLabels.map(option=><option value={option} key={option}/>)}</datalist><datalist id="import-subject-options">{subjectOptions.map(option=><option value={option} key={option}/>)}</datalist></div></section>
   <section className="import-review-list">{rows.map((row,index)=>{const target=row.targetId?existing.find(q=>q.id===row.targetId):undefined;return <details className={`card import-row ${row.matchKind}`} key={row.id} open={row.resolution==='review'||row.matchKind==='conflict'}><summary><div><b>{index+1}. {row.prompt}</b><small>{row.matchKind==='none'?'New question':row.matchKind==='exact'?'Exact match — classifications will merge':row.matchKind==='near'?`Possible duplicate · ${Math.round(row.similarity*100)}% wording overlap`:'Exact wording conflict — different answer key'}</small></div><span className={`import-status ${row.resolution}`}>{row.resolution==='review'?'Review':row.resolution}</span></summary><div className="import-row-body"><ol type="A">{row.choices.map((choice,choiceIndex)=><li className={choiceIndex===row.correctIndex?'good':''} key={choiceIndex}>{choice}{choiceIndex===row.correctIndex?' ✓':''}</li>)}</ol>{target&&<div className="import-match"><b>Existing bank question</b><p>{target.prompt}</p>{row.matchKind==='conflict'&&<p className="bad">The answer key differs. This exact wording cannot be imported as a second copy. Skip it or edit the existing question separately.</p>}</div>}{row.matchKind==='near'&&<div className="import-resolution"><b>How should CramLoop handle this?</b><div className="row" style={{flexWrap:'wrap'}}><button type="button" className={row.resolution==='merge'?'':'secondary'} onClick={()=>patchRow(row.id,{resolution:'merge'})}>Merge into existing</button><button type="button" className={row.resolution==='new'?'':'secondary'} onClick={()=>patchRow(row.id,{resolution:'new'})}>Keep as new</button><button type="button" className="ghost" onClick={()=>patchRow(row.id,{resolution:'skip'})}>Skip</button></div>{row.resolution==='merge'&&<p className="muted">The existing wording and answer key stay unchanged; these imported classifications are added to it.</p>}</div>}{row.matchKind==='exact'&&<div className="row"><button type="button" className={row.resolution==='merge'?'':'secondary'} onClick={()=>patchRow(row.id,{resolution:'merge'})}>Merge tags</button><button type="button" className="ghost" onClick={()=>patchRow(row.id,{resolution:'skip'})}>Skip</button></div>}
    <div className="import-tags"><div><b>Chapters</b><div className="tag-chip-row">{row.chapters.map((tag,tagIndex)=><button className="tag-chip" type="button" onClick={()=>patchRow(row.id,{chapters:row.chapters.filter((_,i)=>i!==tagIndex)})} key={`${tag.number}-${tag.title}-${tagIndex}`}>{chapterLabel(tag)} ×</button>)}{!row.chapters.length&&<span className="muted">Unassigned</span>}</div><TagAdder kind="chapter" options={chapterLabels} onAdd={value=>addChapter(row.id,value)}/></div><div><b>Subjects</b><div className="tag-chip-row">{row.subjects.map((subject,subjectIndex)=><button className="tag-chip" type="button" onClick={()=>patchRow(row.id,{subjects:row.subjects.filter((_,i)=>i!==subjectIndex)})} key={`${subject}-${subjectIndex}`}>{subject} ×</button>)}{!row.subjects.length&&<span className="muted">Unassigned</span>}</div><TagAdder kind="subject" options={subjectOptions} onAdd={value=>addSubject(row.id,value)}/></div></div></div></details>})}</section>
   <form action={action} className="card import-final"><input type="hidden" name="import_rows" value={payload}/><div><h2>3. Import approved questions</h2><p className="muted">This is the first step that writes to your Question Bank.</p></div>{reviewCount>0&&<p className="bad notice">Choose Merge, Keep as new, or Skip for all {reviewCount} possible duplicate{reviewCount===1?'':'s'} first.</p>}<button disabled={reviewCount>0||importCount+mergeCount===0}>Import {importCount+mergeCount} approved question{importCount+mergeCount===1?'':'s'}</button></form></>}
  <style jsx global>{`.import-stager textarea{white-space:pre-wrap;overflow-wrap:anywhere}.import-summary{display:grid;gap:5px;justify-items:end;font-size:.88rem}.import-bulk{margin-top:14px;padding-top:14px;border-top:1px solid #e5e7eb}.import-bulk-grid{display:grid;grid-template-columns:1fr 1fr auto;gap:8px;margin-top:8px}.import-review-list{display:grid;gap:10px}.import-row{padding:0;overflow:hidden}.import-row>summary{list-style:none;display:flex;justify-content:space-between;gap:12px;padding:14px;cursor:pointer}.import-row>summary::-webkit-details-marker{display:none}.import-row>summary b,.import-row>summary small{display:block}.import-row>summary small{color:#64748b;margin-top:4px}.import-row.near{border-color:#f59e0b}.import-row.conflict{border-color:#ef4444}.import-row.exact{border-color:#86efac}.import-status{text-transform:capitalize;font-size:.78rem;font-weight:800;padding:5px 8px;border-radius:999px;background:#eef2ff;color:#4338ca;height:max-content}.import-status.merge{background:#ecfdf5;color:#047857}.import-status.skip{background:#f1f5f9;color:#475569}.import-status.review{background:#fff7ed;color:#c2410c}.import-row-body{padding:0 14px 14px;border-top:1px solid #eef0f4}.import-row-body ol{margin:12px 0}.import-match{padding:10px 12px;background:#f8fafc;border-radius:10px}.import-match p{margin:5px 0}.import-resolution{margin-top:12px}.import-tags{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.tag-chip-row{display:flex;gap:6px;flex-wrap:wrap;margin:7px 0}.tag-chip{background:#eef2ff;color:#4338ca;padding:5px 8px;font-size:.78rem;border-radius:999px}.import-tag-adder{display:grid;grid-template-columns:1fr auto;gap:6px}.import-tag-adder input{margin:0;padding:8px 9px}.import-tag-adder button{padding:8px 10px}.import-final{position:sticky;bottom:8px;z-index:8;box-shadow:0 10px 30px #0f172a22}@media(max-width:700px){.import-summary{justify-items:start}.import-bulk-grid,.import-tags{grid-template-columns:1fr}.import-row>summary{align-items:flex-start}.import-final button{width:100%}}`}</style>
 </div>
}
