import Link from 'next/link'
import { notFound,redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { updateBankQuestion } from '../../actions'

export default async function EditBankQuestion({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string}>}){
  const{id}=await params;const query=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
  const{data:profile}=await supabase.from('profiles').select('role,teacher_approved').eq('id',user.id).single();if(profile?.role!=='teacher'||!profile.teacher_approved)redirect('/dashboard')
  const{data:q}=await supabase.from('question_bank').select('id,prompt,choices,correct_index,content_area,subject_category,chapter_number,chapter_title,explanation,focused_retake_hint,source_type,shared_question_id').eq('id',id).eq('teacher_id',user.id).single();if(!q)notFound()
  const choices=Array.isArray(q.choices)?q.choices.map(String):[]
  return <main className="narrow"><Link href="/question-bank">← Question bank</Link><h1>Edit your question</h1>{q.shared_question_id&&<p className="muted">This question was copied from the shared library. Your edits only affect your personal bank.</p>}{query.error&&<p className="bad">{query.error}</p>}<form action={updateBankQuestion.bind(null,id)} className="card stack"><label>Question</label><textarea name="prompt" required defaultValue={q.prompt}/><div className="settings-grid"><div><label>Chapter number <span className="muted">(optional)</span></label><input name="chapter_number" type="number" min="1" step="1" defaultValue={q.chapter_number??''} placeholder="1"/></div><div><label>Chapter title <span className="muted">(optional)</span></label><input name="chapter_title" defaultValue={q.chapter_title??''} placeholder="Infection Control"/></div></div><label>Subject category</label><input name="subject_category" defaultValue={q.subject_category??q.content_area??''} placeholder="Safety & sanitation"/><p className="muted" style={{marginTop:-8}}>Chapter identifies where the material is taught. Subject category identifies what the question tests. CramLoop can use both when building future exams.</p><label>Answer choices</label>{choices.map((choice:string,i:number)=><div className="row" key={i}><input style={{flex:1}} name="choices" required defaultValue={choice}/><label className="check"><input type="radio" name="correct_index" value={i} defaultChecked={i===q.correct_index}/>Correct</label></div>)}<label>Focused retake hint <span className="muted">(optional)</span></label><textarea name="focused_retake_hint" defaultValue={q.focused_retake_hint??''} placeholder="Hint: shown only during focused retakes. Teach the idea—don’t give the answer away too easily."/><p className="muted" style={{marginTop:-8}}>Only shown during focused retakes when hints are enabled. It is never displayed during the full test. <Link href="/help#focused-hints">Learn more</Link></p><label>Explanation / teaching note</label><textarea name="explanation" defaultValue={q.explanation??''} placeholder="Why is this answer correct?"/><button>Save my version</button></form></main>
}
