import Link from 'next/link'

export const metadata={title:'Trust Center | CramLoop',description:'Security, privacy, student-data, and district review information for CramLoop.'}

const items=[
  {href:'/security',title:'Security',body:'How CramLoop protects accounts, assessment data, transport, browser access, and role-separated workflows.'},
  {href:'/school-privacy',title:'School & Student Privacy',body:'How student information is used for educational purposes, including advertising, access, school authority, and district review.'},
  {href:'/privacy',title:'Privacy Policy',body:'The categories of information CramLoop processes, why it is used, and the choices available to users.'},
  {href:'/subprocessors',title:'Service Providers & Subprocessors',body:'The core infrastructure providers used to host, authenticate, store, and operate CramLoop.'},
  {href:'/data-retention',title:'Data Retention & Deletion',body:'CramLoop’s current retention principles and how eligible information is handled when deletion is requested.'},
  {href:'/terms',title:'Terms of Use',body:'Rules governing accounts, educational use, teacher content, student use, availability, and platform responsibilities.'},
  {href:'/acceptable-use',title:'Acceptable Use',body:'Platform rules covering lawful use, assessment integrity, account security, and prohibited activity.'},
]

export default function TrustPage(){return <main className="narrow"><Link href="/">← CramLoop</Link><h1>Trust Center</h1><p className="lead">Security, privacy, and school-review information for teachers, families, district technology teams, and administrators.</p><section className="card stack"><h2>District network access</h2><p>CramLoop is a browser-based educational assessment and study platform. Normal use requires outbound HTTPS access on TCP port 443 to <b>cramloop.app</b>, <b>www.cramloop.app</b>, and <b>kbouetjaefilebcyotbw.supabase.co</b>. No browser extension, executable, or device-management software is required.</p><p>If a managed device reports <code>ERR_CONNECTION_RESET</code>, district firewall, proxy, SSL-inspection, DNS-filtering, or web-category rules should be checked for these domains.</p></section><div className="grid two">{items.map(item=><section className="card" key={item.href}><h2>{item.title}</h2><p>{item.body}</p><Link className="secondary button-like" href={item.href}>Review {item.title}</Link></section>)}</div><section className="card stack"><h2>School and district reviews</h2><p>CramLoop can provide reasonable technical and privacy information requested during district review, including required domains, service providers, data categories, role-based access, account workflows, and security controls.</p><p>CramLoop does not sell student personal information, does not include third-party advertising in the student experience, and does not use student information for targeted advertising.</p><p>This Trust Center is intended to make initial technical and privacy review easier. A district may still require its own data privacy agreement, security questionnaire, procurement process, or other approval before school-wide deployment.</p></section></main>}
