import Link from 'next/link'
import {notFound,redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'
import {generateAlternateVersion} from '../version-actions'

export default async function TestPreview({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{created?:string,error?:string,source?:string}>}){
 const{id}=await params;const query=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const{data:profile}=await supabase.from('profiles').select('role,teacher_approved').eq('id',user.id).single();if(profile?.role!=='teacher'||!profile.teacher_approved)redirect('/dashboard')
 const{data:test}=await supabase.from('tests').select('id,teacher_id,title,description,status,duration_minutes,passing_score_percent,one_question_per_page,randomize_questions,randomize_choices,questions_per_attempt,questions(id,prompt,position,choices(id,label,position))').eq('id',id).single();if(!test||test.teacher_id!==user.id)notFound()
 const questions=[...(test.questions??[])].sort((a:any,b:any)=>a.position-b.position)
 const fullCount=test.questions_per_attempt||questions.length
 const justCreated=Boolean(query.created)
 const createdLabel=query.created==='blueprint'?'Fresh test generated from your blueprint.':query.created==='alternate'?'Fresh alternate version generated.':'Test created.'
 return <main>
  <div className="row between" style={{alignItems:'flex-start',gap:12,flexWrap:'wrap'}}><div><Link href="/dashboard">← Test library</Link><h1 style={{marginBottom:4}}>Review test</h1><p className="muted" style={{marginTop:0}}>Confirm the student experience, make any last edits, then continue to assignment.</p></div><span className="pill">Teacher preview</span></div>
  <section className="card" style={{padding:'12px 16px'}}><div className="row" style={{gap:8,flexWrap:'wrap',alignItems:'center'}}><span className="pill">1 · Build ✓</span><span aria-hidden>→</span><span className="pill">2 · Review</span><span aria-hidden>→</span><span className="muted">3 · Assign</span><span aria-hidden>→</span><span className="muted">4 · Analyze</span></div></section>
  {query.error&&<p className="bad notice">{query.error}</p>}
  {justCreated&&<div className="notice"><b>{createdLabel}</b><p className="muted">Nothing has been assigned yet. Review it below, edit anything you want, then continue to Assign.</p>{query.created==='alternate'&&query.source&&<p className="muted"><Link href={`/tests/${query.source}/preview`}>View the source version</Link></p>}</div>}
  <section className="card"><div className="row between" style={{alignItems:'flex-start',gap:12,flexWrap:'wrap'}}><div><h2 style={{marginTop:0}}>{test.title}</h2><p>{test.description||'No description'}</p></div><span className="pill">{test.status}</span></div><div className="settings-grid"><div><b>{questions.length}</b><p className="muted">questions in pool</p></div><div><b>{fullCount}</b><p className="muted">shown per full test</p></div><div><b>{test.duration_minutes?`${test.duration_minutes} min`:'Untimed'}</b><p className="muted">time limit</p></div><div><b>{test.passing_score_percent}%</b><p className="muted">passing score</p></div></div><p className="muted">{test.one_question_per_page?'One question per page':'Continuous test'} · {test.randomize_questions?'Question order randomized':'Fixed question order'} · {test.randomize_choices?'Choices randomized':'Fixed choice order'}</p></section>
  <section className="card"><div className="row between" style={{alignItems:'center',gap:12,flexWrap:'wrap'}}><div><h2 style={{margin:0}}>Ready to move on?</h2><p className="muted" style={{margin:'4px 0 0'}}>Editing keeps you in draft. Generate another version for a fresh equivalent, or continue to Assign when this version looks right.</p></div><div className="row" style={{gap:8,flexWrap:'wrap'}}><form action={generateAlternateVersion.bind(null,id)}><button className="secondary" type="submit">↻ Generate another version</button></form><Link className="secondary button" href={`/tests/${id}/edit`}>✎ Edit test</Link><Link className="button" href={`/tests/${id}?step=assign#assign-test`}>Continue to Assign →</Link></div></div><p className="muted field-help">Another version keeps this test’s settings and measured chapter/subject mix, then prioritizes different matching questions from your current question bank.</p></section>
  <div className="notice"><b>Student view preview</b><p className="muted">This shows the test content without creating an attempt or revealing the answer key.</p></div>
  {questions.map((question:any,index:number)=>{const choices=[...(question.choices??[])].sort((a:any,b:any)=>a.position-b.position);return <section className="card" key={question.id}><h2>{index+1}. {question.prompt}</h2>{choices.map((choice:any)=><label className="check" key={choice.id}><input type="radio" disabled name={`preview_${question.id}`}/>{choice.label}</label>)}</section>})}
  <section className="card"><div className="row between" style={{alignItems:'center',gap:12,flexWrap:'wrap'}}><div><b>Review complete?</b><p className="muted" style={{margin:'3px 0 0'}}>Your next step is choosing students, dates, attempts, and testing rules.</p></div><div className="row" style={{gap:8,flexWrap:'wrap'}}><Link className="secondary button" href={`/tests/${id}/edit`}>Edit</Link><Link className="button" href={`/tests/${id}?step=assign#assign-test`}>Continue to Assign →</Link></div></div></section>
 </main>
}
