import Link from 'next/link'
import { login, signup, requestPasswordReset } from './actions'

export default async function Login({searchParams}:{searchParams:Promise<{error?:string,message?:string,role?:string,invite?:string,next?:string}>}){
  const q=await searchParams
  const invitedTeacher=q.role==='teacher'&&Boolean(q.invite)
  const next=q.next?.startsWith('/')&&!q.next.startsWith('//')?q.next:'/dashboard'
  return <main className="narrow"><Link href="/">← Home</Link><h1>{invitedTeacher?'Invited teacher signup':'Sign in'}</h1><p className="muted">Student accounts are open. Teacher tools require a private one-time invite from an approved teacher.</p>{q.error&&<p className="bad notice">{q.error}</p>}{q.message&&<p className="good notice">{q.message}</p>}<form className="card"><input type="hidden" name="next" value={next}/><label>Name <span className="muted">(new accounts)</span></label><input name="full_name"/><label>Email</label><input name="email" type="email" required/><label>Password</label><input name="password" type="password" minLength={6}/>{invitedTeacher?<><input type="hidden" name="role" value="teacher"/><input type="hidden" name="teacher_invite" value={q.invite}/><div className="notice"><b>Teacher invitation</b><p className="muted">This one-time invite will unlock approved teacher tools after account creation and email confirmation.</p></div></>:<input type="hidden" name="role" value="student"/>}{next.startsWith('/share/')&&<p className="good notice">After signing in, you’ll return directly to this shared assignment.</p>}<div className="row"><button formAction={login}>Sign in</button><button className="secondary" formAction={signup}>{invitedTeacher?'Create teacher account':'Create student account'}</button></div><button className="link-button" formAction={requestPasswordReset}>Forgot password?</button><p className="muted">Enter your email above, then choose Forgot password. We’ll email a secure reset link.</p></form></main>
}
