import Link from 'next/link'
import {notFound,redirect} from 'next/navigation'
import {createClient} from '@/lib/supabase/server'

type Row={name:string;best:number;attempts:any[]}
export default async function TestReports({params}:{params:Promise<{id:string}>}){
 const{id}=await params;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const{data:profile}=await supabase.from('profiles').select('role,teacher_approved').eq('id',user.id).single();if(profile?.role!=='teacher'||!profile.teacher_approved)redirect('/dashboard')
 const{data:test}=await supabase.from('tests').select('id,teacher_id,title,passing_score_percent').eq('id',id).single();if(!test||test.teacher_id!==user.id)notFound()
 const{data:attempts}=await supabase.from('attempts').select('id,student_id,attempt_number,score_percent,correct_count,total_questions,started_at,submitted_at,integrity_violation_count,focus_loss_count,fullscreen_exit_count,auto_submitted,student:profiles!attempts_student_id_fkey(full_name)').eq('test_id',id).not('submitted_at','is',null).order('submitted_at',{ascending:false})
 const rows=new Map<string,Row>();for(const a of attempts??[]){const s=Array.isArray((a as any).student)?(a as any).student[0]:(a as any).student;const key=String((a as any).student_id);const row:Row=rows.get(key)??{name:s?.full_name||'Student',best:0,attempts:[]};row.best=Math.max(row.best,Number((a as any).score_percent||0));row.attempts.push(a as any);rows.set(key,row)}
 const completed=attempts??[];const avg=completed.length?Math.round(completed.reduce((sum:number,a:any)=>sum+Number(a.score_percent||0),0)/completed.length):0;const passCount=completed.filter((a:any)=>Number(a.score_percent||0)>=Number(test.passing_score_percent||70)).length
 return <main><div className="row between"><div><Link href="/dashboard">← Test library</Link><h1>{test.title} reports</h1></div><Link className="secondary button" href={`/tests/${id}/preview`}>Student view</Link></div><div className="settings-grid"><section className="card"><b>{completed.length}</b><p className="muted">Completed attempts</p></section><section className="card"><b>{avg}%</b><p className="muted">Average score</p></section><section className="card"><b>{passCount}</b><p className="muted">Passing attempts</p></section></div>{rows.size===0?<section className="card"><p className="muted">No submitted attempts yet.</p></section>:[...rows.entries()].map(([studentId,row])=><section className="card" key={studentId}><div className="row between"><div><h2>{row.name}</h2><p className="muted">{row.attempts.length} completed attempt{row.attempts.length===1?'':'s'}</p></div><strong>Highest grade: {row.best}%</strong></div>{row.attempts.sort((a:any,b:any)=>a.attempt_number-b.attempt_number).map((a:any)=><div className="result-row" key={a.id}><div><b>Attempt {a.attempt_number}</b><p className="muted">{new Date(a.submitted_at).toLocaleString()}{a.auto_submitted?' · Auto-submitted':''}</p></div><div><b>{a.score_percent}%</b><p className="muted">{a.correct_count}/{a.total_questions} correct · {a.integrity_violation_count} integrity event(s)</p></div><Link href={`/attempts/${a.id}`}>Attempt details →</Link></div>)}</section>)}</main>
}
