'use client'
import {ChangeEvent,useMemo,useState} from 'react'

type DraftQuestion={prompt:string;choices:string[];correctIndex:number;contentArea:string;subjectCategory:string;chapterNumber:number|null;chapterTitle:string;focusedRetakeHint:string;sourceType?:string}
type BankQuestion={id:string;prompt:string;choices:string[];correct_index:number;content_area:string|null;subject_category:string|null;chapter_number:number|null;chapter_title:string|null;source_type:string;focused_retake_hint:string|null;imported_collection_id?:string|null;bundle_title?:string|null;source_bucket_key?:string;source_bucket_title?:string}
type PreviousQuestion={id:string;prompt:string;choices:string[];correct_index:number;content_area:string|null;subject_category:string|null;chapter_number:number|null;chapter_title:string|null;focused_retake_hint:string|null;bank_id:string|null}
type PreviousTest={id:string;title:string;updated_at:string;assessment_type?:string|null;chapter_label?:string|null;questions:PreviousQuestion[]}
type ImportSummary={added:number;duplicates:number;errors:string[]}
type SourceBucket={key:string;title:string;kind:'custom'|'bundle'|'collection';bundleId:string|null;collectionIds:string[];questionCount:number}

type WeightedBucket={key:string;title:string;sourceKey:string;chapterKey:string;questions:BankQuestion[]}

const CHOICE_HEADERS=['Choice A','Choice B','Choice C','Choice D','Choice E','Choice F']
function normalize(value:string){return value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function subjectOf(q:{subject_category?:string|null;content_area?:string|null}){return (q.subject_category||q.content_area||'General / untagged').trim()}
function sourceOf(q:BankQuestion){return q.source_bucket_key||'custom'}
function chapterKey(q:{chapter_number?:number|null;chapter_title?:string|null}){return q.chapter_number?`n:${q.chapter_number}|${q.chapter_title||''}`:q.chapter_title?`t:${q.chapter_title}`:'none'}
function chapterText(q:{chapter_number?:number|null;chapter_title?:string|null}){if(q.chapter_number)return `Chapter ${q.chapter_number}${q.chapter_title?` — ${q.chapter_title}`:''}`;return q.chapter_title||'Unchaptered'}
function bucketKey(q:BankQuestion){return `${sourceOf(q)}::${chapterKey(q)}`}
function blankQuestion(chapterNumber:number|null=null,chapterTitle='',subject=''):DraftQuestion{return{prompt:'',choices:['','','',''],correctIndex:0,contentArea:subject,subjectCategory:subject,chapterNumber,chapterTitle,focusedRetakeHint:''}}
function uniqueBank(items:BankQuestion[]){const seen=new Set<string>();return items.filter(q=>{const key=normalize(q.prompt);if(!key||seen.has(key))return false;seen.add(key);return true})}
function uniqueDrafts(items:DraftQuestion[]){const seen=new Set<string>();return items.filter(q=>{const key=normalize(q.prompt);if(!key||seen.has(key))return false;seen.add(key);return true})}
function allocateCounts(labels:string[],weights:Record<string,number>,count:number){const rows=labels.map(label=>{const exact=count*(Number(weights[label])||0)/100;return{label,count:Math.floor(exact),fraction:exact-Math.floor(exact)}});let assigned=rows.reduce((sum,row)=>sum+row.count,0);for(const row of [...rows].sort((a,b)=>b.fraction-a.fraction)){if(assigned>=count)break;row.count++;assigned++}return Object.fromEntries(rows.map(row=>[row.label,row.count])) as Record<string,number>}
function distribute100(labels:string[],maxWeights:Record<string,number>,basis?:Record<string,number>){const result:Record<string,number>=Object.fromEntries(labels.map(label=>[label,0]));for(let point=0;point<100;point++){const candidates=labels.filter(label=>(result[label]||0)<Math.floor(maxWeights[label]??100));if(!candidates.length)break;let best=candidates[0],bestScore=-Infinity;for(const label of candidates){const desire=Math.max(.0001,basis?.[label]??1);const score=desire/(result[label]+1);if(score>bestScore){bestScore=score;best=label}}result[best]=(result[best]||0)+1}return result}
function rebalanceAfterChange(labels:string[],current:Record<string,number>,changed:string,nextValue:number,maxWeights:Record<string,number>){const max=Math.max(0,Math.floor(maxWeights[changed]??100));const changedValue=Math.max(0,Math.min(max,Math.round(nextValue)));const result:Record<string,number>=Object.fromEntries(labels.map(label=>[label,label===changed?changedValue:0]));let remaining=100-changedValue;const others=labels.filter(label=>label!==changed);while(remaining>0){const candidates=others.filter(label=>(result[label]||0)<Math.floor(maxWeights[label]??100));if(!candidates.length)break;let best=candidates[0],bestScore=-Infinity;for(const label of candidates){const desire=Math.max(1,current[label]||1);const score=desire/(result[label]+1);if(score>bestScore){bestScore=score;best=label}}result[best]=(result[best]||0)+1;remaining--}return result}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}

export default function ClassroomTestBuilder({action,bankQuestions=[],previousTests=[],sourceBuckets=[]}:{action:(formData:FormData)=>void;saveMixPresetAction?:unknown;bankQuestions?:BankQuestion[];previousTests?:PreviousTest[];sourceBuckets?:SourceBucket[];bundlePresets?:unknown;initialMixPresets?:unknown}){
 const[assessmentType,setAssessmentType]=useState<'chapter_exam'|'custom'>('chapter_exam')
 const[questions,setQuestions]=useState<DraftQuestion[]>([blankQuestion()])
 const[chapterLabel,setChapterLabel]=useState('')
 const[duration,setDuration]=useState(45)
 const[passingScore,setPassingScore]=useState(70)
 const[singlePage,setSinglePage]=useState(true)
 const[randomize,setRandomize]=useState(false)
 const[questionsPerAttempt,setQuestionsPerAttempt]=useState('')
 const[sourceSearch,setSourceSearch]=useState('')
 const[autoCount,setAutoCount]=useState(20)
 const[selectedBuckets,setSelectedBuckets]=useState<Set<string>>(()=>new Set())
 const[bucketWeights,setBucketWeights]=useState<Record<string,number>>({})
 const[subjectWeights,setSubjectWeights]=useState<Record<string,number>>({})
 const[blueprintError,setBlueprintError]=useState('')
 const[buildSummary,setBuildSummary]=useState('')
 const[importSummary,setImportSummary]=useState<ImportSummary|null>(null)

 const payload=useMemo(()=>JSON.stringify(questions.filter(q=>q.prompt.trim())),[questions])
 const selectedPrompts=useMemo(()=>new Set(questions.map(q=>normalize(q.prompt)).filter(Boolean)),[questions])
 const pool=useMemo(()=>questions.filter(q=>q.prompt.trim()),[questions])
 const requestedCount=questionsPerAttempt?Number(questionsPerAttempt):pool.length
 const countInvalid=pool.length>0&&(requestedCount<1||requestedCount>pool.length)
 const bankById=useMemo(()=>new Map(bankQuestions.map(q=>[q.id,q])),[bankQuestions])
 const sourceTitleMap=useMemo(()=>new Map(sourceBuckets.map(source=>[source.key,source.title])),[sourceBuckets])
 const needle=normalize(sourceSearch)
 const visibleBank=useMemo(()=>bankQuestions.filter(q=>!needle||normalize(`${q.prompt} ${chapterText(q)} ${subjectOf(q)} ${q.source_bucket_title??q.bundle_title??''}`).includes(needle)),[bankQuestions,needle])
 const visiblePrevious=useMemo(()=>previousTests.map(t=>({...t,questions:t.questions.filter(q=>!needle||normalize(`${t.title} ${t.chapter_label??''} ${q.prompt} ${chapterText(q)} ${subjectOf(q)}`).includes(needle))})).filter(t=>t.questions.length),[previousTests,needle])
 const allPrevious=useMemo(()=>previousTests.flatMap(t=>t.questions),[previousTests])

 const bucketOptions=useMemo(()=>{const map=new Map<string,WeightedBucket>();for(const q of bankQuestions){const key=bucketKey(q),sourceKey=sourceOf(q),chapter=chapterKey(q),title=`${sourceTitleMap.get(sourceKey)||q.source_bucket_title||q.bundle_title||'Saved questions'} · ${chapterText(q)}`;const item=map.get(key)??{key,title,sourceKey,chapterKey:chapter,questions:[]};item.questions.push(q);map.set(key,item)}return[...map.values()].map(item=>({...item,questions:uniqueBank(item.questions)})).sort((a,b)=>a.title.localeCompare(b.title,undefined,{numeric:true}))},[bankQuestions,sourceTitleMap])
 const bucketMap=useMemo(()=>new Map(bucketOptions.map(bucket=>[bucket.key,bucket])),[bucketOptions])
 const selectedBucketKeys=useMemo(()=>bucketOptions.map(bucket=>bucket.key).filter(key=>selectedBuckets.has(key)),[bucketOptions,selectedBuckets])
 const selectedCandidates=useMemo(()=>uniqueBank(selectedBucketKeys.flatMap(key=>bucketMap.get(key)?.questions||[])),[selectedBucketKeys,bucketMap])
 const desiredCount=Math.max(1,Math.round(autoCount||1))
 const bucketMaxWeights=useMemo(()=>Object.fromEntries(selectedBucketKeys.map(key=>{const available=bucketMap.get(key)?.questions.length||0;return[key,Math.min(100,Math.floor(available*100/desiredCount))]})),[selectedBucketKeys,bucketMap,desiredCount])
 const bucketCapacityTotal=selectedBucketKeys.reduce((sum,key)=>sum+(bucketMap.get(key)?.questions.length||0),0)
 const effectiveBucketWeights=useMemo(()=>{if(!selectedBucketKeys.length)return{};if(selectedBucketKeys.length===1)return{[selectedBucketKeys[0]]:Math.min(100,bucketMaxWeights[selectedBucketKeys[0]]??100)};const hasAll=selectedBucketKeys.every(key=>Number.isFinite(bucketWeights[key]));if(hasAll&&Math.round(selectedBucketKeys.reduce((sum,key)=>sum+(bucketWeights[key]||0),0))===100)return Object.fromEntries(selectedBucketKeys.map(key=>[key,Math.min(bucketWeights[key]||0,bucketMaxWeights[key]??100)]));return distribute100(selectedBucketKeys,bucketMaxWeights)},[selectedBucketKeys,bucketWeights,bucketMaxWeights])
 const bucketTotal=selectedBucketKeys.reduce((sum,key)=>sum+(effectiveBucketWeights[key]||0),0)
 const bucketTargets=useMemo(()=>allocateCounts(selectedBucketKeys,effectiveBucketWeights,desiredCount),[selectedBucketKeys,effectiveBucketWeights,desiredCount])

 const subjectCategories=useMemo(()=>[...new Set(selectedCandidates.map(subjectOf))].sort(),[selectedCandidates])
 const subjectCapacityCounts=useMemo(()=>{const result:Record<string,number>={};for(const subject of subjectCategories){let capacity=0;for(const key of selectedBucketKeys){const target=bucketTargets[key]||0;const available=(bucketMap.get(key)?.questions||[]).filter(q=>subjectOf(q)===subject).length;capacity+=Math.min(target,available)}result[subject]=capacity}return result},[subjectCategories,selectedBucketKeys,bucketTargets,bucketMap])
 const subjectMaxWeights=useMemo(()=>Object.fromEntries(subjectCategories.map(subject=>[subject,Math.min(100,Math.floor((subjectCapacityCounts[subject]||0)*100/desiredCount))])),[subjectCategories,subjectCapacityCounts,desiredCount])
 const effectiveSubjectWeights=useMemo(()=>{if(!subjectCategories.length)return{};const complete=subjectCategories.every(subject=>Number.isFinite(subjectWeights[subject]));if(complete&&Math.round(subjectCategories.reduce((sum,subject)=>sum+(subjectWeights[subject]||0),0))===100)return Object.fromEntries(subjectCategories.map(subject=>[subject,Math.min(subjectWeights[subject]||0,subjectMaxWeights[subject]??100)]));return distribute100(subjectCategories,subjectMaxWeights,subjectCapacityCounts)},[subjectCategories,subjectWeights,subjectMaxWeights,subjectCapacityCounts])
 const subjectTotal=subjectCategories.reduce((sum,subject)=>sum+(effectiveSubjectWeights[subject]||0),0)

 function draftFromBank(q:BankQuestion):DraftQuestion{const subject=subjectOf(q);return{prompt:q.prompt,choices:[...q.choices],correctIndex:q.correct_index,contentArea:subject,subjectCategory:subject,chapterNumber:q.chapter_number??null,chapterTitle:q.chapter_title??'',focusedRetakeHint:q.focused_retake_hint??'',sourceType:'copied'}}
 function draftFromPrevious(q:PreviousQuestion):DraftQuestion{const match=q.bank_id?bankById.get(q.bank_id):undefined;if(match)return draftFromBank(match);const subject=subjectOf(q);return{prompt:q.prompt,choices:[...q.choices],correctIndex:q.correct_index,contentArea:subject,subjectCategory:subject,chapterNumber:q.chapter_number??null,chapterTitle:q.chapter_title??'',focusedRetakeHint:q.focused_retake_hint??'',sourceType:'previous_test'}}
 function addDrafts(items:DraftQuestion[]){setQuestions(current=>{const existing=new Set(current.map(q=>normalize(q.prompt)).filter(Boolean));const additions=uniqueDrafts(items).filter(q=>!existing.has(normalize(q.prompt)));const blank=current.length===1&&!current[0].prompt.trim()&&current[0].choices.every(x=>!x.trim());return additions.length?[...(blank?[]:current),...additions]:current})}
 function replaceDrafts(items:DraftQuestion[]){const next=uniqueDrafts(items);setQuestions(next.length?next:[blankQuestion()]);setQuestionsPerAttempt('')}
 function removePrompts(prompts:string[]){const keys=new Set(prompts.map(normalize));setQuestions(current=>{const next=current.filter(q=>!keys.has(normalize(q.prompt)));return next.length?next:[blankQuestion()]})}
 function toggleBank(items:BankQuestion[]){const all=items.length>0&&items.every(q=>selectedPrompts.has(normalize(q.prompt)));if(all)removePrompts(items.map(q=>q.prompt));else addDrafts(items.map(draftFromBank))}
 function togglePrevious(items:PreviousQuestion[]){const all=items.length>0&&items.every(q=>selectedPrompts.has(normalize(q.prompt)));if(all)removePrompts(items.map(q=>q.prompt));else addDrafts(items.map(draftFromPrevious))}
 function toggleBucket(key:string){setSelectedBuckets(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);const keys=bucketOptions.map(bucket=>bucket.key).filter(bucketKey=>next.has(bucketKey));const max=Object.fromEntries(keys.map(bucketKey=>{const available=bucketMap.get(bucketKey)?.questions.length||0;return[bucketKey,Math.min(100,Math.floor(available*100/desiredCount))]}));setBucketWeights(distribute100(keys,max));setSubjectWeights({});return next});setBlueprintError('');setBuildSummary('')}
 function changeBucketWeight(key:string,value:number){const next=rebalanceAfterChange(selectedBucketKeys,effectiveBucketWeights,key,value,bucketMaxWeights);setBucketWeights(next);setSubjectWeights({});setBlueprintError('');setBuildSummary('')}
 function changeSubjectWeight(subject:string,value:number){setSubjectWeights(rebalanceAfterChange(subjectCategories,effectiveSubjectWeights,subject,value,subjectMaxWeights));setBlueprintError('');setBuildSummary('')}

 function buildSmart(){
  setBlueprintError('');setBuildSummary('')
  if(!selectedBucketKeys.length){setBlueprintError('Select at least one source bucket.');return}
  if(bucketCapacityTotal<desiredCount){setBlueprintError(`These buckets only contain ${bucketCapacityTotal} unique questions. Add another bucket or lower the requested question count.`);return}
  if(Math.round(bucketTotal)!==100){setBlueprintError(`The selected buckets cannot supply 100% of a ${desiredCount}-question test. Add another bucket or lower the question count.`);return}
  if(Math.round(subjectTotal)!==100){setBlueprintError('The available subjects cannot fill the requested test with the current bucket weights. Add another bucket or lower the question count.');return}
  const sourceTargets=allocateCounts(selectedBucketKeys,effectiveBucketWeights,desiredCount)
  const subjectTargets=allocateCounts(subjectCategories,effectiveSubjectWeights,desiredCount)
  const bucketUsed:Record<string,number>={},subjectUsed:Record<string,number>={},used=new Set<string>(),chosen:BankQuestion[]=[]
  while(chosen.length<desiredCount){
    const available=selectedCandidates.filter(q=>!used.has(normalize(q.prompt)))
    if(!available.length)break
    let best:BankQuestion|undefined,bestScore=-Infinity
    for(const q of available){const bucket=bucketKey(q),subject=subjectOf(q),bucketNeed=(sourceTargets[bucket]||0)-(bucketUsed[bucket]||0),subjectNeed=(subjectTargets[subject]||0)-(subjectUsed[subject]||0);if(bucketNeed<=0)continue;const score=1000+bucketNeed+(subjectNeed>0?500+subjectNeed:subjectNeed)+Math.random();if(score>bestScore){bestScore=score;best=q}}
    if(!best)break
    const key=normalize(best.prompt);used.add(key);chosen.push(best);const bucket=bucketKey(best),subject=subjectOf(best);bucketUsed[bucket]=(bucketUsed[bucket]||0)+1;subjectUsed[subject]=(subjectUsed[subject]||0)+1
  }
  if(chosen.length<desiredCount){setBlueprintError(`Only ${chosen.length} questions could satisfy both the bucket and subject mix. Reduce a constrained percentage, add another bucket, or lower the question count.`);return}
  replaceDrafts(chosen.map(draftFromBank));setAssessmentType('chapter_exam');setRandomize(true)
  const chapters=[...new Set(chosen.map(chapterText))];setChapterLabel(chapters.join(', '))
  setBuildSummary(`Built ${chosen.length} questions · ${selectedBucketKeys.map(key=>`${bucketMap.get(key)?.title||key} ${bucketUsed[key]||0}`).join(' · ')}`)
 }

 function updateQuestion(index:number,patch:Partial<DraftQuestion>){setQuestions(c=>c.map((q,i)=>i===index?{...q,...patch}:q))}
 function updateChoice(qi:number,ci:number,value:string){setQuestions(c=>c.map((q,i)=>i===qi?{...q,choices:q.choices.map((x,j)=>j===ci?value:x)}:q))}
 function addQuestion(){const first=selectedBucketKeys[0]?bucketMap.get(selectedBucketKeys[0])?.questions[0]:undefined;setQuestions(c=>[...c,blankQuestion(first?.chapter_number??null,first?.chapter_title??'','')])}
 function removeQuestion(index:number){setQuestions(c=>{const next=c.filter((_,i)=>i!==index);return next.length?next:[blankQuestion()]})}
 function addChoice(qi:number){setQuestions(c=>c.map((q,i)=>i===qi&&q.choices.length<6?{...q,choices:[...q.choices,'']}:q))}
 function removeChoice(qi:number,ci:number){setQuestions(c=>c.map((q,i)=>{if(i!==qi||q.choices.length<=2)return q;const choices=q.choices.filter((_,j)=>j!==ci);const correctIndex=q.correctIndex===ci?0:q.correctIndex>ci?q.correctIndex-1:q.correctIndex;return{...q,choices,correctIndex}}))}

 async function importCsv(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;const rows=parseCsv(await file.text());if(rows.length<2){setImportSummary({added:0,duplicates:0,errors:['The file has no question rows.']});event.target.value='';return}const headers=rows[0].map(h=>h.trim().toLowerCase());const idx=(name:string)=>headers.indexOf(name.toLowerCase());const qIndex=idx('Question'),correctCol=idx('Correct Answer'),subjectCol=idx('Subject Category'),legacyAreaCol=idx('Content Area'),chapterNumberCol=idx('Chapter Number'),chapterTitleCol=idx('Chapter Title'),choiceCols=CHOICE_HEADERS.map(idx);const missing=[] as string[];if(qIndex<0)missing.push('Question');if(correctCol<0)missing.push('Correct Answer');if(choiceCols[0]<0)missing.push('Choice A');if(choiceCols[1]<0)missing.push('Choice B');if(missing.length){setImportSummary({added:0,duplicates:0,errors:[`Missing required columns: ${missing.join(', ')}`]});event.target.value='';return}const existing=new Set([...questions.map(q=>normalize(q.prompt)),...bankQuestions.map(q=>normalize(q.prompt))].filter(Boolean));const imported:DraftQuestion[]=[];const errors:string[]=[];let duplicates=0;rows.slice(1).forEach((row,rowOffset)=>{const prompt=(row[qIndex]??'').trim();if(!prompt||prompt.toUpperCase().startsWith('EXAMPLE'))return;const key=normalize(prompt);if(existing.has(key)){duplicates++;return}const rawChoices=choiceCols.map(col=>col>=0?(row[col]??'').trim():'');const choices=rawChoices.filter(Boolean);if(choices.length<2){errors.push(`Row ${rowOffset+2}: at least two answer choices are required.`);return}const answer=(row[correctCol]??'').trim();let rawCorrect=-1;if(/^[A-F]$/i.test(answer))rawCorrect=answer.toUpperCase().charCodeAt(0)-65;else if(/^[1-6]$/.test(answer))rawCorrect=Number(answer)-1;else rawCorrect=rawChoices.findIndex(c=>c.toLowerCase()===answer.toLowerCase());if(rawCorrect<0||!rawChoices[rawCorrect]){errors.push(`Row ${rowOffset+2}: invalid Correct Answer.`);return}const chapterRaw=chapterNumberCol>=0?(row[chapterNumberCol]??'').trim():'';const chapterNumber=chapterRaw?Number(chapterRaw):null;if(chapterNumber!==null&&(!Number.isInteger(chapterNumber)||chapterNumber<1)){errors.push(`Row ${rowOffset+2}: Chapter Number must be a positive whole number.`);return}const subject=(subjectCol>=0?(row[subjectCol]??'').trim():'')||(legacyAreaCol>=0?(row[legacyAreaCol]??'').trim():'');const chapterTitle=chapterTitleCol>=0?(row[chapterTitleCol]??'').trim():'';imported.push({prompt,choices,correctIndex:rawChoices.slice(0,rawCorrect).filter(Boolean).length,contentArea:subject,subjectCategory:subject,chapterNumber,chapterTitle,focusedRetakeHint:'',sourceType:'import'});existing.add(key)});addDrafts(imported);setImportSummary({added:imported.length,duplicates,errors});event.target.value=''}

 const bankGroups=useMemo(()=>{const map=new Map<string,BankQuestion[]>();for(const q of visibleBank){const key=`${q.source_bucket_title||q.bundle_title||'Saved questions'} · ${chapterText(q)} · ${subjectOf(q)}`;map.set(key,[...(map.get(key)||[]),q])}return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0],undefined,{numeric:true}))},[visibleBank])

 return <form action={action} className="stack">
  <section className="card"><h2>What are you building?</h2><div className="mode-grid"><button type="button" className={assessmentType==='chapter_exam'?'mode-card active':'mode-card'} onClick={()=>{setAssessmentType('chapter_exam');setDuration(45)}}><b>Chapter / Smart Exam</b><span>Choose weighted source buckets and let CramLoop build the output.</span></button><button type="button" className={assessmentType==='custom'?'mode-card active':'mode-card'} onClick={()=>setAssessmentType('custom')}><b>Custom Test</b><span>Mix any saved, imported, previous, or new questions.</span></button></div><input type="hidden" name="assessment_type" value={assessmentType}/><input type="hidden" name="exam_preset" value="custom"/><label>Test title</label><input name="title" required placeholder={chapterLabel?`${chapterLabel} Exam`:'Chapter Exam'}/><input type="hidden" name="chapter_label" value={chapterLabel}/><label>Summary / description</label><textarea name="description" rows={3}/><div className="settings-grid"><div><label>Timer (minutes)</label><input name="duration_minutes" type="number" min="0" max="600" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></div><div><label>Passing score (%)</label><input name="passing_score" type="number" min="0" max="100" value={passingScore} onChange={e=>setPassingScore(Number(e.target.value))}/></div></div><label className="check"><input name="single_page" type="checkbox" checked={singlePage} onChange={e=>setSinglePage(e.target.checked)}/> Show one question per page</label><label className="check"><input name="randomize" type="checkbox" checked={randomize} onChange={e=>setRandomize(e.target.checked)}/> Randomize question order</label><p className="muted">Assignment rules, attempts, due dates, and focused remediation are configured when you share the test.</p></section>

  {assessmentType==='chapter_exam'&&<section className="card smart-builder-v3"><div className="row between" style={{alignItems:'flex-start',gap:12,flexWrap:'wrap'}}><div><h2 style={{marginBottom:4}}>Smart test</h2><p className="muted" style={{marginTop:0}}>Select the chapter/resource buckets CramLoop may use. Weighting always stays at 100% and is limited by real question availability.</p></div><span className="pill">{selectedCandidates.length} unique available</span></div>
   <div className="smart-step"><div className="row between"><div><b>1. Select source buckets</b><p className="muted field-help">A bucket is a specific question source + chapter.</p></div><span className="pill">{selectedBucketKeys.length} selected</span></div><div className="bucket-grid">{bucketOptions.map(bucket=><label className="check bucket-choice" key={bucket.key}><input type="checkbox" checked={selectedBuckets.has(bucket.key)} onChange={()=>toggleBucket(bucket.key)}/><span><b>{bucket.title}</b><small>{bucket.questions.length} unique questions</small></span></label>)}</div></div>
   {selectedBucketKeys.length>0&&<div className="smart-step"><div className="row between" style={{gap:10,alignItems:'end',flexWrap:'wrap'}}><div><b>2. Bucket weight</b><p className="muted field-help">With two equal buckets this starts 50/50. Add a third and CramLoop automatically rebalances. Moving one slider automatically reduces/increases the others.</p></div><div><label>Questions to build</label><input className="count-input" type="number" min="1" max="200" value={autoCount} onChange={e=>{setAutoCount(Math.max(1,Number(e.target.value)||1));setBucketWeights({});setSubjectWeights({});setBlueprintError('')}}/></div></div><div className="slider-list">{selectedBucketKeys.map(key=>{const bucket=bucketMap.get(key)!;const max=bucketMaxWeights[key]??0;return <label className="slider-row" key={key}><span>{bucket.title}<small>{bucket.questions.length} available · max {max}% at {desiredCount} questions</small></span><input type="range" min="0" max={max} step="1" value={Math.min(effectiveBucketWeights[key]||0,max)} onChange={e=>changeBucketWeight(key,Number(e.target.value))}/><b>{Math.round(effectiveBucketWeights[key]||0)}%</b></label>})}</div><p className={Math.round(bucketTotal)===100?'good':'bad'}>Bucket total: {Math.round(bucketTotal)}% / 100%{bucketCapacityTotal<desiredCount?` · only ${bucketCapacityTotal} questions available for ${desiredCount} requested`:''}</p></div>}
   {selectedBucketKeys.length>0&&subjectCategories.length>0&&<div className="smart-step"><div className="row between"><div><b>3. Question output by subject</b><p className="muted field-help">CramLoop starts from the subject availability inside your weighted buckets. Adjust any subject and the other subjects rebalance automatically.</p></div><span className="pill">{subjectCategories.length} subjects</span></div><div className="slider-list">{subjectCategories.map(subject=>{const max=subjectMaxWeights[subject]??0;return <label className="slider-row" key={subject}><span>{subject}<small>{subjectCapacityCounts[subject]||0} possible at current bucket mix · max {max}%</small></span><input type="range" min="0" max={max} step="1" value={Math.min(effectiveSubjectWeights[subject]||0,max)} onChange={e=>changeSubjectWeight(subject,Number(e.target.value))}/><b>{Math.round(effectiveSubjectWeights[subject]||0)}%</b></label>})}</div><p className={Math.round(subjectTotal)===100?'good':'bad'}>Subject total: {Math.round(subjectTotal)}% / 100%</p></div>}
   {blueprintError&&<p className="bad notice">{blueprintError}</p>}{buildSummary&&<p className="good notice">{buildSummary}</p>}<button type="button" onClick={buildSmart} disabled={!selectedBucketKeys.length||Math.round(bucketTotal)!==100||Math.round(subjectTotal)!==100||bucketCapacityTotal<desiredCount}>Build smart test</button><p className="muted field-help">A percentage can never be pushed above what the selected buckets can actually provide for the requested test size.</p>
  </section>}

  <section className="card pool-builder"><div className="row between"><div><h2>Question pool</h2><p className="muted">Review the smart selection or manually choose from your saved sources.</p></div><span className="pill">{pool.length} selected</span></div><label>Questions per attempt</label><input name="questions_per_attempt" type="number" min="1" max={Math.max(1,pool.length)} value={questionsPerAttempt} onChange={e=>setQuestionsPerAttempt(e.target.value)} placeholder={pool.length?`All ${pool.length} selected`:'Select questions first'}/><p className="muted field-help">Leave blank to use the entire selected pool. Set a smaller number for a fresh randomized subset on each attempt.</p>{countInvalid&&<p className="bad">Choose a count from 1 to {pool.length}.</p>}<label>Search saved sources</label><input value={sourceSearch} onChange={e=>setSourceSearch(e.target.value)} placeholder="Search source, chapter, subject, question, or prior test"/>
   <details className="bank-picker" open><summary><b>Question Bank ({bankQuestions.length})</b></summary>{bankGroups.length===0?<p className="muted">No matching saved questions.</p>:bankGroups.map(([group,items])=>{const selected=items.filter(q=>selectedPrompts.has(normalize(q.prompt))).length;const all=selected===items.length;return <details className="bank-section" key={group} open={Boolean(sourceSearch)}><summary><span><b>{group}</b> <span className="muted">{selected}/{items.length} selected</span></span></summary><label className="check section-select"><input type="checkbox" checked={all} ref={el=>{if(el)el.indeterminate=selected>0&&!all}} onChange={()=>toggleBank(items)}/><b>Select all</b></label>{items.map(item=><label className="check bank-question-check" key={item.id}><input type="checkbox" checked={selectedPrompts.has(normalize(item.prompt))} onChange={()=>toggleBank([item])}/><span>{item.prompt}<small>{chapterText(item)} · {subjectOf(item)} · {item.source_bucket_title||item.bundle_title||'Saved question'}</small></span></label>)}</details>})}</details>
   <details className="bank-picker"><summary><b>Previous Tests ({previousTests.length})</b></summary>{visiblePrevious.length===0?<p className="muted">{previousTests.length?'No previous tests match this search.':'Your previous tests will appear here.'}</p>:visiblePrevious.map(test=>{const selected=test.questions.filter(q=>selectedPrompts.has(normalize(q.prompt))).length;const all=selected===test.questions.length;return <details className="bank-section" key={test.id}><summary><span><b>{test.title}</b> <span className="muted">{test.chapter_label?`${test.chapter_label} · `:''}{selected}/{test.questions.length} selected</span></span></summary><label className="check section-select"><input type="checkbox" checked={all} ref={el=>{if(el)el.indeterminate=selected>0&&!all}} onChange={()=>togglePrevious(test.questions)}/><b>Select all from this test</b></label>{test.questions.map(item=><label className="check bank-question-check" key={item.id}><input type="checkbox" checked={selectedPrompts.has(normalize(item.prompt))} onChange={()=>togglePrevious([item])}/><span>{item.prompt}<small>{chapterText(item)} · {subjectOf(item)}</small></span></label>)}</details>})}</details>
  </section>

  <details className="card"><summary><b>Import multiple questions</b></summary><p className="muted">The template supports Chapter Number, Chapter Title, and Subject Category so imports immediately become reusable smart-test buckets.</p><ol><li><a href="/templates/question-import-template.csv" download><b>Download the question import template</b></a>.</li><li>Keep the header row unchanged.</li><li>Chapter fields are optional; Subject Category is recommended.</li><li>Enter A-F, 1-6, or exact answer text in Correct Answer.</li></ol><label className="button-like secondary" htmlFor="classroom-question-import">Choose CSV file</label><input id="classroom-question-import" type="file" accept=".csv,text/csv" onChange={importCsv} style={{display:'none'}}/>{importSummary&&<div className="notice" style={{marginTop:14}}><b>Import check</b><p>{importSummary.added} added · {importSummary.duplicates} exact duplicates skipped.</p>{importSummary.errors.map((x,i)=><p className="bad" key={i}>{x}</p>)}</div>}</details>

  <details className="card" open={pool.length>0}><summary><b>Edit selected questions ({pool.length})</b></summary>{questions.map((q,qi)=><section className="question-summary" key={`${normalize(q.prompt)}-${qi}`}><div className="row between"><h3>Question {qi+1}</h3><button className="ghost danger" type="button" onClick={()=>removeQuestion(qi)}>Remove</button></div><div className="settings-grid"><div><label>Chapter number <span className="muted">(optional)</span></label><input type="number" min="1" step="1" value={q.chapterNumber??''} onChange={e=>updateQuestion(qi,{chapterNumber:e.target.value?Number(e.target.value):null})} placeholder="1"/></div><div><label>Chapter title <span className="muted">(optional)</span></label><input value={q.chapterTitle} onChange={e=>updateQuestion(qi,{chapterTitle:e.target.value})} placeholder="Infection Control"/></div></div><label>Subject category</label><input value={q.subjectCategory} onChange={e=>updateQuestion(qi,{subjectCategory:e.target.value,contentArea:e.target.value})} placeholder="Safety & sanitation"/><textarea required rows={3} value={q.prompt} onChange={e=>updateQuestion(qi,{prompt:e.target.value})} placeholder="Type the question"/><label>Focused retake hint <span className="muted">(optional)</span></label><textarea rows={2} value={q.focusedRetakeHint} onChange={e=>updateQuestion(qi,{focusedRetakeHint:e.target.value})} placeholder="Teach the idea without giving away the answer."/><p className="muted">Select the circle beside the correct answer.</p>{q.choices.map((choice,ci)=><div className="choice-editor" key={ci}><input type="radio" name={`correct-${qi}`} checked={q.correctIndex===ci} onChange={()=>updateQuestion(qi,{correctIndex:ci})}/><input required value={choice} onChange={e=>updateChoice(qi,ci,e.target.value)} placeholder={`Answer choice ${ci+1}`}/><button className="ghost" type="button" onClick={()=>removeChoice(qi,ci)} disabled={q.choices.length<=2}>×</button></div>)}<button className="secondary" type="button" onClick={()=>addChoice(qi)} disabled={q.choices.length>=6}>+ Answer choice</button></section>)}<button className="secondary" type="button" onClick={addQuestion}>+ Write a new question</button></details>
  <input type="hidden" name="questions" value={payload}/><div className="row"><button type="submit" disabled={!pool.length||countInvalid}>Save test</button><span className="muted">Pool {pool.length} · Attempt {pool.length?requestedCount:0}</span></div>
  <style jsx global>{`.smart-builder-v3 .smart-step{padding:16px 0;border-top:1px solid #edf0f5}.bucket-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:8px;margin-top:10px}.bucket-choice{padding:10px 12px;border:1px solid #e4e7ef;border-radius:12px;background:#fff}.bucket-choice span,.slider-row span{display:block}.bucket-choice small,.slider-row small{display:block;color:#64748b;margin-top:2px}.count-input{width:110px;margin:0}.slider-list{display:grid;gap:13px;margin-top:12px}.slider-row{display:grid;grid-template-columns:minmax(190px,1.25fr) minmax(170px,2fr) 48px;gap:12px;align-items:center}.slider-row input[type=range]{width:100%;margin:0;accent-color:#4f46e5}.slider-row b{text-align:right;font-variant-numeric:tabular-nums}@media(max-width:700px){.bucket-grid{grid-template-columns:1fr}.slider-row{grid-template-columns:1fr 52px;gap:5px 8px}.slider-row span{grid-column:1/-1}.slider-row input[type=range]{grid-column:1}.slider-row b{grid-column:2}.count-input{width:100%}}`}</style>
 </form>
}
