'use client'
import {ChangeEvent,useMemo,useState} from 'react'

type DraftQuestion={prompt:string;choices:string[];correctIndex:number;contentArea:string;focusedRetakeHint:string;sourceType?:string}
type BankQuestion={id:string;prompt:string;choices:string[];correct_index:number;content_area:string|null;source_type:string;focused_retake_hint:string|null;bundle_title?:string|null}
type PreviousQuestion={id:string;prompt:string;choices:string[];correct_index:number;content_area:string|null;focused_retake_hint:string|null;bank_id:string|null}
type PreviousTest={id:string;title:string;updated_at:string;assessment_type?:string|null;chapter_label?:string|null;questions:PreviousQuestion[]}
type ImportSummary={added:number;duplicates:number;errors:string[]}
type TopicSource={topic:string;bank:BankQuestion[];previous:PreviousQuestion[];previousTests:number}

const CHOICE_HEADERS=['Choice A','Choice B','Choice C','Choice D','Choice E','Choice F']
function blankQuestion(area=''):DraftQuestion{return{prompt:'',choices:['','','',''],correctIndex:0,contentArea:area,focusedRetakeHint:''}}
function normalize(value:string){return value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}

export default function ClassroomTestBuilder({action,bankQuestions=[],previousTests=[]}:{action:(formData:FormData)=>void;bankQuestions?:BankQuestion[];previousTests?:PreviousTest[]}){
 const[assessmentType,setAssessmentType]=useState<'chapter_exam'|'custom'>('chapter_exam')
 const[questions,setQuestions]=useState<DraftQuestion[]>([blankQuestion()])
 const[chapterLabel,setChapterLabel]=useState('')
 const[duration,setDuration]=useState(45)
 const[passingScore,setPassingScore]=useState(70)
 const[singlePage,setSinglePage]=useState(true)
 const[randomize,setRandomize]=useState(false)
 const[questionsPerAttempt,setQuestionsPerAttempt]=useState('')
 const[sourceSearch,setSourceSearch]=useState('')
 const[autoCount,setAutoCount]=useState(20)
 const[importSummary,setImportSummary]=useState<ImportSummary|null>(null)

 const payload=useMemo(()=>JSON.stringify(questions.filter(q=>q.prompt.trim())),[questions])
 const selectedPrompts=useMemo(()=>new Set(questions.map(q=>normalize(q.prompt)).filter(Boolean)),[questions])
 const pool=useMemo(()=>questions.filter(q=>q.prompt.trim()),[questions])
 const requestedCount=questionsPerAttempt?Number(questionsPerAttempt):pool.length
 const countInvalid=pool.length>0&&(requestedCount<1||requestedCount>pool.length)
 const bankById=useMemo(()=>new Map(bankQuestions.map(q=>[q.id,q])),[bankQuestions])
 const needle=normalize(sourceSearch)
 const visibleBank=useMemo(()=>bankQuestions.filter(q=>!needle||normalize(`${q.prompt} ${q.content_area??''} ${q.bundle_title??''}`).includes(needle)),[bankQuestions,needle])
 const visiblePrevious=useMemo(()=>previousTests.map(t=>({...t,questions:t.questions.filter(q=>!needle||normalize(`${t.title} ${t.chapter_label??''} ${q.prompt} ${q.content_area??''}`).includes(needle))})).filter(t=>t.questions.length),[previousTests,needle])

 const topicSources=useMemo<TopicSource[]>(()=>{
  const map=new Map<string,{bank:BankQuestion[];previous:PreviousQuestion[];tests:Set<string>}>()
  const ensure=(topic:string)=>{const clean=topic.trim()||'General / untagged';if(!map.has(clean))map.set(clean,{bank:[],previous:[],tests:new Set()});return map.get(clean)!}
  for(const q of bankQuestions)ensure(q.content_area||'General / untagged').bank.push(q)
  for(const test of previousTests){
   const chapter=(test.chapter_label||'').trim()
   if(test.assessment_type==='chapter_exam'&&chapter){const entry=ensure(chapter);entry.tests.add(test.id);for(const q of test.questions)entry.previous.push(q)}
   for(const q of test.questions){const topic=(q.content_area||'').trim();if(topic){const entry=ensure(topic);entry.tests.add(test.id);entry.previous.push(q)}}
  }
  return[...map.entries()].map(([topic,value])=>({topic,bank:value.bank,previous:value.previous,previousTests:value.tests.size})).sort((a,b)=>(b.bank.length+b.previous.length)-(a.bank.length+a.previous.length)||a.topic.localeCompare(b.topic))
 },[bankQuestions,previousTests])

 function draftFromBank(q:BankQuestion):DraftQuestion{return{prompt:q.prompt,choices:[...q.choices],correctIndex:q.correct_index,contentArea:q.content_area??'',focusedRetakeHint:q.focused_retake_hint??'',sourceType:'copied'}}
 function draftFromPrevious(q:PreviousQuestion):DraftQuestion{const match=q.bank_id?bankById.get(q.bank_id):undefined;return match?draftFromBank(match):{prompt:q.prompt,choices:[...q.choices],correctIndex:q.correct_index,contentArea:q.content_area??'',focusedRetakeHint:q.focused_retake_hint??'',sourceType:'previous_test'}}
 function uniqueDrafts(items:DraftQuestion[]){const seen=new Set<string>();return items.filter(q=>{const key=normalize(q.prompt);if(!key||seen.has(key))return false;seen.add(key);return true})}
 function addDrafts(items:DraftQuestion[]){setQuestions(current=>{const existing=new Set(current.map(q=>normalize(q.prompt)).filter(Boolean));const additions=uniqueDrafts(items).filter(q=>!existing.has(normalize(q.prompt)));const blank=current.length===1&&!current[0].prompt.trim()&&current[0].choices.every(x=>!x.trim());return additions.length?[...(blank?[]:current),...additions]:current})}
 function replaceDrafts(items:DraftQuestion[],topic:string){const next=uniqueDrafts(items);setQuestions(next.length?next:[blankQuestion(topic)]);setQuestionsPerAttempt('')}
 function removePrompts(prompts:string[]){const keys=new Set(prompts.map(normalize));setQuestions(current=>{const next=current.filter(q=>!keys.has(normalize(q.prompt)));return next.length?next:[blankQuestion(chapterLabel)]})}
 function toggleBank(items:BankQuestion[]){const all=items.length>0&&items.every(q=>selectedPrompts.has(normalize(q.prompt)));if(all)removePrompts(items.map(q=>q.prompt));else addDrafts(items.map(draftFromBank))}
 function togglePrevious(items:PreviousQuestion[]){const all=items.length>0&&items.every(q=>selectedPrompts.has(normalize(q.prompt)));if(all)removePrompts(items.map(q=>q.prompt));else addDrafts(items.map(draftFromPrevious))}
 function autoBuild(source:TopicSource){
  const topic=source.topic==='General / untagged'?'':source.topic
  setAssessmentType('chapter_exam');setChapterLabel(topic);setRandomize(false)
  const bank=source.bank.map(draftFromBank)
  const bankKeys=new Set(bank.map(q=>normalize(q.prompt)))
  const fromPrevious=source.previous.map(draftFromPrevious).filter(q=>!bankKeys.has(normalize(q.prompt)))
  const candidates=uniqueDrafts([...bank,...fromPrevious])
  const count=Math.max(1,Math.min(autoCount||20,candidates.length))
  replaceDrafts(candidates.slice(0,count),topic)
 }
 function addTopic(source:TopicSource){setAssessmentType('chapter_exam');setChapterLabel(source.topic==='General / untagged'?'':source.topic);addDrafts([...source.bank.map(draftFromBank),...source.previous.map(draftFromPrevious)])}
 function updateQuestion(index:number,patch:Partial<DraftQuestion>){setQuestions(c=>c.map((q,i)=>i===index?{...q,...patch}:q))}
 function updateChoice(qi:number,ci:number,value:string){setQuestions(c=>c.map((q,i)=>i===qi?{...q,choices:q.choices.map((x,j)=>j===ci?value:x)}:q))}
 function addQuestion(){setQuestions(c=>[...c,blankQuestion(chapterLabel)])}
 function removeQuestion(index:number){setQuestions(c=>{const next=c.filter((_,i)=>i!==index);return next.length?next:[blankQuestion(chapterLabel)]})}
 function addChoice(qi:number){setQuestions(c=>c.map((q,i)=>i===qi&&q.choices.length<6?{...q,choices:[...q.choices,'']}:q))}
 function removeChoice(qi:number,ci:number){setQuestions(c=>c.map((q,i)=>{if(i!==qi||q.choices.length<=2)return q;const choices=q.choices.filter((_,j)=>j!==ci);const correctIndex=q.correctIndex===ci?0:q.correctIndex>ci?q.correctIndex-1:q.correctIndex;return{...q,choices,correctIndex}}))}

 async function importCsv(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;const rows=parseCsv(await file.text());if(rows.length<2){setImportSummary({added:0,duplicates:0,errors:['The file has no question rows.']});event.target.value='';return}const headers=rows[0].map(h=>h.trim().toLowerCase());const idx=(name:string)=>headers.indexOf(name.toLowerCase());const qIndex=idx('Question'),correctCol=idx('Correct Answer'),areaCol=idx('Content Area'),choiceCols=CHOICE_HEADERS.map(idx);const missing=[] as string[];if(qIndex<0)missing.push('Question');if(correctCol<0)missing.push('Correct Answer');if(choiceCols[0]<0)missing.push('Choice A');if(choiceCols[1]<0)missing.push('Choice B');if(missing.length){setImportSummary({added:0,duplicates:0,errors:[`Missing required columns: ${missing.join(', ')}`]});event.target.value='';return}const existing=new Set([...questions.map(q=>normalize(q.prompt)),...bankQuestions.map(q=>normalize(q.prompt))].filter(Boolean));const imported:DraftQuestion[]=[];const errors:string[]=[];let duplicates=0;rows.slice(1).forEach((row,rowOffset)=>{const prompt=(row[qIndex]??'').trim();if(!prompt||prompt.toUpperCase().startsWith('EXAMPLE'))return;const key=normalize(prompt);if(existing.has(key)){duplicates++;return}const rawChoices=choiceCols.map(col=>col>=0?(row[col]??'').trim():'');const choices=rawChoices.filter(Boolean);if(choices.length<2){errors.push(`Row ${rowOffset+2}: at least two answer choices are required.`);return}const answer=(row[correctCol]??'').trim();let rawCorrect=-1;if(/^[A-F]$/i.test(answer))rawCorrect=answer.toUpperCase().charCodeAt(0)-65;else if(/^[1-6]$/.test(answer))rawCorrect=Number(answer)-1;else rawCorrect=rawChoices.findIndex(c=>c.toLowerCase()===answer.toLowerCase());if(rawCorrect<0||!rawChoices[rawCorrect]){errors.push(`Row ${rowOffset+2}: invalid Correct Answer.`);return}imported.push({prompt,choices,correctIndex:rawChoices.slice(0,rawCorrect).filter(Boolean).length,contentArea:areaCol>=0?(row[areaCol]??'').trim():chapterLabel,focusedRetakeHint:'',sourceType:'import'});existing.add(key)});addDrafts(imported);setImportSummary({added:imported.length,duplicates,errors});event.target.value=''}

 return <form action={action} className="stack">
  <section className="card"><h2>What are you building?</h2><div className="mode-grid"><button type="button" className={assessmentType==='chapter_exam'?'mode-card active':'mode-card'} onClick={()=>{setAssessmentType('chapter_exam');setDuration(45);setRandomize(false)}}><b>Chapter Exam</b><span>Build a chapter, unit, or topic assessment quickly from saved content.</span></button><button type="button" className={assessmentType==='custom'?'mode-card active':'mode-card'} onClick={()=>setAssessmentType('custom')}><b>Custom Test</b><span>Mix any saved, imported, previous, or new questions.</span></button></div><input type="hidden" name="assessment_type" value={assessmentType}/><input type="hidden" name="exam_preset" value="custom"/>{assessmentType==='chapter_exam'&&<div><label>Chapter / unit / topic</label><input name="chapter_label" value={chapterLabel} onChange={e=>setChapterLabel(e.target.value)} placeholder="Example: Chapter 5 — Infection Control"/></div>}<label>Test title</label><input name="title" required placeholder={chapterLabel?`${chapterLabel} Exam`:'Chapter Exam'}/><label>Summary / description</label><textarea name="description" rows={3}/><div className="settings-grid"><div><label>Timer (minutes)</label><input name="duration_minutes" type="number" min="0" max="600" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></div><div><label>Passing score (%)</label><input name="passing_score" type="number" min="0" max="100" value={passingScore} onChange={e=>setPassingScore(Number(e.target.value))}/></div></div><label className="check"><input name="single_page" type="checkbox" checked={singlePage} onChange={e=>setSinglePage(e.target.checked)}/> Show one question per page</label><label className="check"><input name="randomize" type="checkbox" checked={randomize} onChange={e=>setRandomize(e.target.checked)}/> Randomize question order</label><p className="muted">Assignment rules, attempt limits, due dates, and focused remediation are configured when you share the test.</p></section>

  {assessmentType==='chapter_exam'&&topicSources.length>0&&<section className="card"><div className="row between"><div><h2>Auto-build a chapter exam</h2><p className="muted">CramLoop combines matching questions from your bank, imported resources, and previous chapter exams. Exact duplicates are removed automatically.</p></div><span className="pill">{topicSources.length} topics</span></div><div className="settings-grid"><div><label>Questions to build</label><input type="number" min="1" max="200" value={autoCount} onChange={e=>setAutoCount(Math.max(1,Number(e.target.value)||1))}/></div><div><label>How selection works</label><p className="muted field-help">Saved/imported bank questions are used first, then prior exams fill any gaps. You can edit the result before saving.</p></div></div><div className="mode-grid">{topicSources.slice(0,18).map(source=>{const uniqueCount=new Set([...source.bank.map(q=>normalize(q.prompt)),...source.previous.map(q=>normalize(q.prompt))]).size;return <div className="mode-card" key={source.topic}><b>{source.topic}</b><span>{uniqueCount} usable · {source.bank.length} bank/imported · {source.previousTests} prior test{source.previousTests===1?'':'s'}</span><div className="row" style={{marginTop:10}}><button type="button" onClick={()=>autoBuild(source)}>Build {Math.min(autoCount,uniqueCount)}</button><button type="button" className="secondary" onClick={()=>addTopic(source)}>Add all</button></div></div>})}</div>{topicSources.length>18&&<p className="muted">Showing the 18 topics with the most reusable content. Use search below for the rest.</p>}</section>}

  <section className="card pool-builder"><div className="row between"><div><h2>Build the question pool</h2><p className="muted">Reuse saved questions instead of retyping them. You can edit the selected copy before saving.</p></div><span className="pill">{pool.length} selected</span></div><label>Questions per attempt</label><input name="questions_per_attempt" type="number" min="1" max={Math.max(1,pool.length)} value={questionsPerAttempt} onChange={e=>setQuestionsPerAttempt(e.target.value)} placeholder={pool.length?`All ${pool.length} selected`:'Select questions first'}/><p className="muted field-help">Leave blank to use the entire pool. Set a smaller number to draw a fresh randomized subset on each attempt.</p>{countInvalid&&<p className="bad">Choose a count from 1 to {pool.length}.</p>}<label>Search saved sources</label><input value={sourceSearch} onChange={e=>setSourceSearch(e.target.value)} placeholder="Search question, topic, resource, or previous test"/>

   <details className="bank-picker" open><summary><b>Question Bank ({bankQuestions.length})</b></summary>{visibleBank.length===0?<p className="muted">No matching saved questions.</p>:topicSources.map(source=>{const items=visibleBank.filter(q=>(q.content_area||'General / untagged').trim()===source.topic);if(!items.length)return null;const selected=items.filter(q=>selectedPrompts.has(normalize(q.prompt))).length;const all=selected===items.length;return <details className="bank-section" key={source.topic} open={Boolean(sourceSearch)}><summary><span><b>{source.topic}</b> <span className="muted">{selected}/{items.length} selected</span></span></summary><label className="check section-select"><input type="checkbox" checked={all} ref={el=>{if(el)el.indeterminate=selected>0&&!all}} onChange={()=>toggleBank(items)}/><b>Select all in topic</b></label>{items.map(item=><label className="check bank-question-check" key={item.id}><input type="checkbox" checked={selectedPrompts.has(normalize(item.prompt))} onChange={()=>toggleBank([item])}/><span>{item.prompt}<small>{item.bundle_title||'Saved question'} · {item.choices.length} choices</small></span></label>)}</details>})}</details>

   <details className="bank-picker"><summary><b>Previous Tests ({previousTests.length})</b></summary>{visiblePrevious.length===0?<p className="muted">{previousTests.length?'No previous tests match this search.':'Your previous tests will appear here.'}</p>:visiblePrevious.map(test=>{const selected=test.questions.filter(q=>selectedPrompts.has(normalize(q.prompt))).length;const all=selected===test.questions.length;return <details className="bank-section" key={test.id}><summary><span><b>{test.title}</b> <span className="muted">{test.chapter_label?`${test.chapter_label} · `:''}{selected}/{test.questions.length} selected</span></span></summary><label className="check section-select"><input type="checkbox" checked={all} ref={el=>{if(el)el.indeterminate=selected>0&&!all}} onChange={()=>togglePrevious(test.questions)}/><b>Select all from this test</b></label>{test.questions.map(item=><label className="check bank-question-check" key={item.id}><input type="checkbox" checked={selectedPrompts.has(normalize(item.prompt))} onChange={()=>togglePrevious([item])}/><span>{item.prompt}<small>{item.content_area||test.chapter_label||'General / untagged'}</small></span></label>)}</details>})}</details>
  </section>

  <details className="card"><summary><b>Import multiple questions</b></summary><p className="muted">Use the same reusable CSV template for chapter exams or custom tests.</p><ol><li><a href="/templates/question-import-template.csv" download><b>Download the question import template</b></a>.</li><li>Keep the header row unchanged.</li><li>Enter A-F, 1-6, or exact answer text in Correct Answer.</li><li>Upload the CSV below.</li></ol><label className="button-like secondary" htmlFor="classroom-question-import">Choose CSV file</label><input id="classroom-question-import" type="file" accept=".csv,text/csv" onChange={importCsv} style={{display:'none'}}/>{importSummary&&<div className="notice" style={{marginTop:14}}><b>Import check</b><p>{importSummary.added} added · {importSummary.duplicates} exact duplicates skipped.</p>{importSummary.errors.map((x,i)=><p className="bad" key={i}>{x}</p>)}</div>}</details>

  <details className="card" open={pool.length>0}><summary><b>Edit selected questions ({pool.length})</b></summary>{questions.map((q,qi)=><section className="question-summary" key={`${normalize(q.prompt)}-${qi}`}><div className="row between"><h3>Question {qi+1}</h3><button className="ghost danger" type="button" onClick={()=>removeQuestion(qi)}>Remove</button></div><label>Question topic <span className="muted">(optional)</span></label><input value={q.contentArea} onChange={e=>updateQuestion(qi,{contentArea:e.target.value})}/><textarea required rows={3} value={q.prompt} onChange={e=>updateQuestion(qi,{prompt:e.target.value})} placeholder="Type the question"/><label>Focused retake hint <span className="muted">(optional)</span></label><textarea rows={2} value={q.focusedRetakeHint} onChange={e=>updateQuestion(qi,{focusedRetakeHint:e.target.value})} placeholder="Teach the idea without giving away the answer."/><p className="muted">Select the circle beside the correct answer.</p>{q.choices.map((choice,ci)=><div className="choice-editor" key={ci}><input type="radio" name={`correct-${qi}`} checked={q.correctIndex===ci} onChange={()=>updateQuestion(qi,{correctIndex:ci})}/><input required value={choice} onChange={e=>updateChoice(qi,ci,e.target.value)} placeholder={`Answer choice ${ci+1}`}/><button className="ghost" type="button" onClick={()=>removeChoice(qi,ci)} disabled={q.choices.length<=2}>×</button></div>)}<button className="secondary" type="button" onClick={()=>addChoice(qi)} disabled={q.choices.length>=6}>+ Answer choice</button></section>)}<button className="secondary" type="button" onClick={addQuestion}>+ Write a new question</button></details>
  <input type="hidden" name="questions" value={payload}/><div className="row"><button type="submit" disabled={!pool.length||countInvalid}>Save test</button><span className="muted">Pool {pool.length} · Attempt {pool.length?requestedCount:0}</span></div>
 </form>
}
