'use client'
import { ChangeEvent, useMemo, useState } from 'react'

type DraftQuestion={prompt:string;choices:string[];correctIndex:number;contentArea:string;focusedRetakeHint:string;sourceType?:string}
type BankQuestion={id:string;prompt:string;choices:string[];correct_index:number;content_area:string|null;source_type:string;focused_retake_hint:string|null;bundle_title?:string|null}
type PreviousQuestion={id:string;prompt:string;choices:string[];correct_index:number;content_area:string|null;focused_retake_hint:string|null;bank_id:string|null}
type PreviousTest={id:string;title:string;updated_at:string;questions:PreviousQuestion[]}
type ImportSummary={added:number;duplicates:number;nearDuplicates:string[];errors:string[]}

const PSI_AREAS=['Licensing & Texas Rules','Safety, Sanitation & Infection Control','Hair & Scalp Care','Haircutting & Styling','Chemical Texture Services','Haircoloring & Lightening','Skin Care','Nail Care']
const CHOICE_HEADERS=['Choice A','Choice B','Choice C','Choice D','Choice E','Choice F']

function blankQuestion(area=PSI_AREAS[1]):DraftQuestion{return{prompt:'',choices:['','','',''],correctIndex:0,contentArea:area,focusedRetakeHint:''}}
function normalizeQuestion(value:string){return value.toLowerCase().replace(/[^a-z0-9\s]/g,' ').replace(/\s+/g,' ').trim()}
function similarity(a:string,b:string){const aa=new Set(normalizeQuestion(a).split(' ').filter(Boolean)),bb=new Set(normalizeQuestion(b).split(' ').filter(Boolean));if(!aa.size||!bb.size)return 0;let shared=0;aa.forEach(x=>{if(bb.has(x))shared++});return(2*shared)/(aa.size+bb.size)}
function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[];let cell='';let quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){row.push(cell);cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&text[i+1]==='\n')i++;row.push(cell);cell='';if(row.some(x=>x.trim()))rows.push(row);row=[]}else cell+=ch}row.push(cell);if(row.some(x=>x.trim()))rows.push(row);return rows}

export default function TestBuilder({action,bankQuestions=[],previousTests=[]}:{action:(formData:FormData)=>void;bankQuestions?:BankQuestion[];previousTests?:PreviousTest[]}){
 const[questions,setQuestions]=useState<DraftQuestion[]>([blankQuestion()])
 const[assessmentType,setAssessmentType]=useState<'psi_practice'|'chapter_exam'|'custom'>('psi_practice')
 const[preset,setPreset]=useState('tdlr_operator_written');const[duration,setDuration]=useState(120);const[passingScore,setPassingScore]=useState(70);const[singlePage,setSinglePage]=useState(true);const[randomize,setRandomize]=useState(true)
 const[importSummary,setImportSummary]=useState<ImportSummary|null>(null);const[sourceSearch,setSourceSearch]=useState('');const[questionsPerAttempt,setQuestionsPerAttempt]=useState('')
 const payload=useMemo(()=>JSON.stringify(questions.filter(q=>q.prompt.trim())),[questions])
 const selectedPrompts=useMemo(()=>new Set(questions.map(q=>normalizeQuestion(q.prompt)).filter(Boolean)),[questions])
 const pool=useMemo(()=>questions.filter(q=>q.prompt.trim()),[questions])
 const distribution=useMemo(()=>{const counts=new Map<string,number>();for(const q of pool){const area=q.contentArea.trim()||'General / untagged';counts.set(area,(counts.get(area)||0)+1)}return[...counts.entries()].map(([area,count])=>({area,count,pct:pool.length?Math.round(count/pool.length*100):0})).sort((a,b)=>b.count-a.count)},[pool])
 const requestedCount=questionsPerAttempt?Number(questionsPerAttempt):pool.length
 const countInvalid=pool.length>0&&(requestedCount<1||requestedCount>pool.length)
 const bankById=useMemo(()=>new Map(bankQuestions.map(q=>[q.id,q])),[bankQuestions])
 const needle=normalizeQuestion(sourceSearch)
 const groupedBank=useMemo(()=>{const bundles=new Map<string,Map<string,BankQuestion[]>>();for(const item of bankQuestions){if(needle&&!normalizeQuestion(`${item.prompt} ${item.content_area??''} ${item.bundle_title??''}`).includes(needle))continue;const bundle=item.bundle_title||'My custom questions';const area=item.content_area||'General / untagged';if(!bundles.has(bundle))bundles.set(bundle,new Map());const areas=bundles.get(bundle)!;areas.set(area,[...(areas.get(area)||[]),item])}return[...bundles.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([bundle,areas])=>[bundle,[...areas.entries()].sort((a,b)=>a[0].localeCompare(b[0]))] as const)},[bankQuestions,needle])
 const visiblePrevious=useMemo(()=>previousTests.map(test=>{const titleMatch=needle&&normalizeQuestion(test.title).includes(needle);const qs=!needle||titleMatch?test.questions:test.questions.filter(q=>normalizeQuestion(`${q.prompt} ${q.content_area??''}`).includes(needle));return{...test,questions:qs}}).filter(t=>t.questions.length),[previousTests,needle])

 function applyType(value:'psi_practice'|'chapter_exam'|'custom'){setAssessmentType(value);if(value==='psi_practice'){setPreset('tdlr_operator_written');setDuration(120);setPassingScore(70);setSinglePage(true);setRandomize(true)}else if(value==='chapter_exam'){setPreset('custom');setDuration(45);setPassingScore(70);setSinglePage(true);setRandomize(false)}else setPreset('custom')}
 function updateQuestion(index:number,patch:Partial<DraftQuestion>){setQuestions(c=>c.map((q,i)=>i===index?{...q,...patch}:q))}
 function updateChoice(qi:number,ci:number,value:string){setQuestions(c=>c.map((q,i)=>i===qi?{...q,choices:q.choices.map((x,j)=>j===ci?value:x)}:q))}
 function addQuestion(){setQuestions(c=>[...c,blankQuestion(assessmentType==='psi_practice'?PSI_AREAS[1]:'')])}
 function removeQuestion(index:number){setQuestions(c=>c.length===1?[blankQuestion(assessmentType==='psi_practice'?PSI_AREAS[1]:'')]:c.filter((_,i)=>i!==index))}
 function addChoice(qi:number){setQuestions(c=>c.map((q,i)=>i===qi&&q.choices.length<6?{...q,choices:[...q.choices,'']}:q))}
 function removeChoice(qi:number,ci:number){setQuestions(c=>c.map((q,i)=>{if(i!==qi||q.choices.length<=2)return q;const choices=q.choices.filter((_,j)=>j!==ci);const correctIndex=q.correctIndex===ci?0:q.correctIndex>ci?q.correctIndex-1:q.correctIndex;return{...q,choices,correctIndex}}))}
 function draftFromBank(item:BankQuestion):DraftQuestion{return{prompt:item.prompt,choices:[...item.choices],correctIndex:item.correct_index,contentArea:item.content_area??'',focusedRetakeHint:item.focused_retake_hint??'',sourceType:'copied'}}
 function draftFromPrevious(item:PreviousQuestion):DraftQuestion{const bank=item.bank_id?bankById.get(item.bank_id):undefined;return bank?draftFromBank(bank):{prompt:item.prompt,choices:[...item.choices],correctIndex:item.correct_index,contentArea:item.content_area??'',focusedRetakeHint:item.focused_retake_hint??'',sourceType:'previous_test'}}
 function addDrafts(items:DraftQuestion[]){setQuestions(current=>{const existing=new Set(current.map(q=>normalizeQuestion(q.prompt)).filter(Boolean));const additions=items.filter(i=>!existing.has(normalizeQuestion(i.prompt)));const blank=current.length===1&&!current[0].prompt.trim()&&current[0].choices.every(c=>!c.trim());return additions.length?[...(blank?[]:current),...additions]:current})}
 function removePrompts(prompts:string[]){const keys=new Set(prompts.map(normalizeQuestion));setQuestions(current=>{const next=current.filter(q=>!keys.has(normalizeQuestion(q.prompt)));return next.length?next:[blankQuestion(assessmentType==='psi_practice'?PSI_AREAS[1]:'')]})}
 function toggleItems<T>(items:T[],prompt:(x:T)=>string,draft:(x:T)=>DraftQuestion){const all=items.length>0&&items.every(i=>selectedPrompts.has(normalizeQuestion(prompt(i))));if(all)removePrompts(items.map(prompt));else addDrafts(items.map(draft))}
 function nearestBank(prompt:string){let best:BankQuestion|null=null,bestScore=0;for(const item of bankQuestions){const s=similarity(prompt,item.prompt);if(s>bestScore&&normalizeQuestion(prompt)!==normalizeQuestion(item.prompt)){best=item;bestScore=s}}return best&&bestScore>=0.72?{item:best,score:bestScore}:null}

 async function importCsv(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;const rows=parseCsv(await file.text());if(rows.length<2){setImportSummary({added:0,duplicates:0,nearDuplicates:[],errors:['The file has no question rows.']});event.target.value='';return}const headers=rows[0].map(h=>h.trim().toLowerCase());const idx=(name:string)=>headers.indexOf(name.toLowerCase());const qIndex=idx('Question'),correctCol=idx('Correct Answer'),areaCol=idx('Content Area'),choiceCols=CHOICE_HEADERS.map(idx);const missing:string[]=[];if(qIndex<0)missing.push('Question');if(correctCol<0)missing.push('Correct Answer');if(choiceCols[0]<0)missing.push('Choice A');if(choiceCols[1]<0)missing.push('Choice B');if(missing.length){setImportSummary({added:0,duplicates:0,nearDuplicates:[],errors:[`Missing required columns: ${missing.join(', ')}`]});event.target.value='';return}const existing=new Set([...questions.map(q=>normalizeQuestion(q.prompt)),...bankQuestions.map(q=>normalizeQuestion(q.prompt))].filter(Boolean));const imported:DraftQuestion[]=[];const errors:string[]=[];const nearDuplicates:string[]=[];let duplicates=0;rows.slice(1).forEach((row,rowOffset)=>{const rowNumber=rowOffset+2;const prompt=(row[qIndex]??'').trim();if(!prompt||prompt.toUpperCase().startsWith('EXAMPLE'))return;const normalized=normalizeQuestion(prompt);if(existing.has(normalized)){duplicates++;return}const rawChoices=choiceCols.map(col=>col>=0?(row[col]??'').trim():'');const choices=rawChoices.filter(Boolean);if(choices.length<2){errors.push(`Row ${rowNumber}: at least two answer choices are required.`);return}const answer=(row[correctCol]??'').trim();let rawCorrect=-1;if(/^[A-F]$/i.test(answer))rawCorrect=answer.toUpperCase().charCodeAt(0)-65;else if(/^[1-6]$/.test(answer))rawCorrect=Number(answer)-1;else rawCorrect=rawChoices.findIndex(c=>c.toLowerCase()===answer.toLowerCase());if(rawCorrect<0||!rawChoices[rawCorrect]){errors.push(`Row ${rowNumber}: invalid Correct Answer.`);return}const near=nearestBank(prompt);if(near)nearDuplicates.push(`Row ${rowNumber}: “${prompt}” may duplicate “${near.item.prompt}”.`);imported.push({prompt,choices,correctIndex:rawChoices.slice(0,rawCorrect).filter(Boolean).length,contentArea:areaCol>=0?(row[areaCol]??'').trim():'',focusedRetakeHint:'',sourceType:'import'});existing.add(normalized)});if(imported.length)addDrafts(imported);setImportSummary({added:imported.length,duplicates,nearDuplicates,errors});event.target.value=''}

 return <form action={action} className="stack">
  <section className="card"><h2>What are you building?</h2><div className="mode-grid"><button type="button" className={assessmentType==='psi_practice'?'mode-card active':'mode-card'} onClick={()=>applyType('psi_practice')}><b>PSI Practice Exam</b><span>State-board-style practice built from your selected question pool.</span></button><button type="button" className={assessmentType==='chapter_exam'?'mode-card active':'mode-card'} onClick={()=>applyType('chapter_exam')}><b>Chapter Exam</b><span>Any chapter, unit, or classroom assessment.</span></button><button type="button" className={assessmentType==='custom'?'mode-card active':'mode-card'} onClick={()=>applyType('custom')}><b>Custom Test</b><span>Build reusable assessment content, then choose delivery rules when sharing.</span></button></div><input type="hidden" name="assessment_type" value={assessmentType}/><input type="hidden" name="exam_preset" value={preset}/>{assessmentType==='psi_practice'&&<div className="notice"><b>Texas Cosmetology Operator practice mode</b><p className="muted">Choose the approved question pool and CramLoop will preserve its subject mix when generating each full attempt.</p></div>}{assessmentType==='chapter_exam'&&<div><label>Chapter / unit / topic</label><input name="chapter_label" placeholder="Example: Chapter 5 — Infection Control"/></div>}<label>Test title</label><input name="title" required placeholder={assessmentType==='psi_practice'?'Texas Cosmetology Operator Practice Exam':'Chapter Exam'}/><label>Summary / description</label><textarea name="description" rows={3}/><div className="settings-grid"><div><label>Timer (minutes)</label><input name="duration_minutes" type="number" min="0" max="600" value={duration} onChange={e=>setDuration(Number(e.target.value))}/></div><div><label>Passing score (%)</label><input name="passing_score" type="number" min="0" max="100" value={passingScore} onChange={e=>setPassingScore(Number(e.target.value))}/></div></div><label className="check"><input name="single_page" type="checkbox" checked={singlePage} onChange={e=>setSinglePage(e.target.checked)}/> Show one question per page</label><label className="check"><input name="randomize" type="checkbox" checked={randomize} onChange={e=>setRandomize(e.target.checked)}/> Randomize question order</label><p className="muted">Due dates, attempt limits, focused-retake requirements, and assignment access are chosen later when you share this test.</p></section>

  <section className="card pool-builder"><div className="row between"><div><h2>Build the question pool</h2><p className="muted">Choose from your bank or previous tests. A question selected in one place stays selected everywhere it appears.</p></div><span className="pill">{pool.length} selected</span></div><div><label>Questions per full test</label><input name="questions_per_attempt" type="number" min="1" max={Math.max(1,pool.length)} value={questionsPerAttempt} onChange={e=>setQuestionsPerAttempt(e.target.value)} placeholder={pool.length?`All ${pool.length} selected`:'Select questions first'}/><p className="muted field-help">Leave blank to use the entire selected pool. A smaller count draws a new subject-balanced sample from the approved pool.</p>{countInvalid&&<p className="bad">Choose a count from 1 to {pool.length}.</p>}</div>
   <div className="distribution-panel"><div className="row between"><b>Live subject distribution</b><span className="muted">Pool {pool.length} · Full test {pool.length?requestedCount:0}</span></div>{!distribution.length?<p className="muted">Select questions to see the test focus.</p>:distribution.map(row=><div className="distribution-row" key={row.area}><div className="row between"><span>{row.area}</span><b>{row.count} · {row.pct}%</b></div><div className="distribution-track"><span style={{width:`${row.pct}%`}}/></div></div>)}</div>
   <label>Search all question sources</label><input value={sourceSearch} onChange={e=>setSourceSearch(e.target.value)} placeholder="Search question, subject, bundle, or previous test"/>

   <details className="bank-picker" open><summary><b>My Question Bank ({bankQuestions.length})</b></summary>{groupedBank.length===0?<p className="muted">No matching saved questions.</p>:groupedBank.map(([bundle,areas])=>{const bundleItems=areas.flatMap(([,items])=>items);const selected=bundleItems.filter(i=>selectedPrompts.has(normalizeQuestion(i.prompt))).length;const all=selected===bundleItems.length;return <details className="bank-section" key={bundle} open={Boolean(sourceSearch)}><summary><span><b>{bundle}</b> <span className="muted">{selected}/{bundleItems.length} selected</span></span></summary><label className="check section-select"><input type="checkbox" checked={all} ref={el=>{if(el)el.indeterminate=selected>0&&!all}} onChange={()=>toggleItems(bundleItems,i=>i.prompt,draftFromBank)}/><b>Select entire bundle</b></label>{areas.map(([area,items])=>{const areaSelected=items.filter(i=>selectedPrompts.has(normalizeQuestion(i.prompt))).length;const areaAll=areaSelected===items.length;return <details className="bank-section" key={`${bundle}-${area}`} open={Boolean(sourceSearch)}><summary><span><b>{area}</b> <span className="muted">{areaSelected}/{items.length}</span></span></summary><label className="check section-select"><input type="checkbox" checked={areaAll} ref={el=>{if(el)el.indeterminate=areaSelected>0&&!areaAll}} onChange={()=>toggleItems(items,i=>i.prompt,draftFromBank)}/><b>Select all in section</b></label>{items.map(item=>{const checked=selectedPrompts.has(normalizeQuestion(item.prompt));return <label className="check bank-question-check" key={item.id}><input type="checkbox" checked={checked} onChange={()=>toggleItems([item],i=>i.prompt,draftFromBank)}/><span>{item.prompt}<small>{item.choices.length} choices{item.focused_retake_hint?' · focused hint saved':''}</small></span></label>})}</details>})}</details>})}</details>

   <details className="bank-picker" open><summary><b>Previous Tests ({previousTests.length})</b></summary>{visiblePrevious.length===0?<p className="muted">{previousTests.length?'No previous tests match this search.':'Your saved tests will appear here.'}</p>:visiblePrevious.map(test=>{const selected=test.questions.filter(q=>selectedPrompts.has(normalizeQuestion(q.prompt))).length;const all=selected===test.questions.length;return <details className="bank-section" key={test.id} open={Boolean(sourceSearch)}><summary><span><b>{test.title}</b> <span className="muted">{selected}/{test.questions.length} selected</span></span></summary><label className="check section-select"><input type="checkbox" checked={all} ref={el=>{if(el)el.indeterminate=selected>0&&!all}} onChange={()=>toggleItems(test.questions,i=>i.prompt,draftFromPrevious)}/><b>Select all from this test</b></label>{test.questions.map(item=>{const checked=selectedPrompts.has(normalizeQuestion(item.prompt));return <label className="check bank-question-check" key={item.id}><input type="checkbox" checked={checked} onChange={()=>toggleItems([item],i=>i.prompt,draftFromPrevious)}/><span>{item.prompt}<small>{item.content_area||'General / untagged'}{item.bank_id?' · Bank':''}</small></span></label>})}</details>})}</details>
  </section>

  <details className="card"><summary><b>Import multiple questions</b></summary><p className="muted">Download the template, fill one question per row, export as CSV, and upload it here.</p><ol><li><a href="/templates/question-import-template.csv" download><b>Download the question import template</b></a>.</li><li>Keep the header row unchanged.</li><li>Enter A-F, 1-6, or exact answer text in Correct Answer.</li><li>Upload the saved CSV below.</li></ol><label className="button-like secondary" htmlFor="question-import">Choose CSV file</label><input id="question-import" type="file" accept=".csv,text/csv" onChange={importCsv} style={{display:'none'}}/>{importSummary&&<div className="notice" style={{marginTop:14}}><b>Import check</b><p>{importSummary.added} added · {importSummary.duplicates} exact duplicates skipped · {importSummary.nearDuplicates.length} possible duplicates flagged.</p>{importSummary.nearDuplicates.slice(0,6).map((x,i)=><p className="muted" key={i}>⚠ {x}</p>)}{importSummary.errors.map((x,i)=><p className="bad" key={i}>{x}</p>)}</div>}</details>

  <details className="card"><summary><b>Edit selected questions ({pool.length})</b></summary>{questions.map((q,qi)=>{const near=q.prompt.trim()?nearestBank(q.prompt):null;return <section className="question-summary" key={`${normalizeQuestion(q.prompt)}-${qi}`}><div className="row between"><h3>Question {qi+1}</h3><button className="ghost danger" type="button" onClick={()=>removeQuestion(qi)}>Remove</button></div>{assessmentType==='psi_practice'?<><label>PSI content area</label><select value={q.contentArea} onChange={e=>updateQuestion(qi,{contentArea:e.target.value})}>{PSI_AREAS.map(area=><option key={area}>{area}</option>)}</select></>:<><label>Question topic <span className="muted">(optional)</span></label><input value={q.contentArea} onChange={e=>updateQuestion(qi,{contentArea:e.target.value})}/></>}<textarea required rows={3} value={q.prompt} onChange={e=>updateQuestion(qi,{prompt:e.target.value})} placeholder="Type the question"/>{near&&<div className="notice"><b>Possible duplicate</b><p className="muted">Similar saved question: “{near.item.prompt}”</p></div>}<label>Focused retake hint <span className="muted">(optional)</span></label><textarea rows={2} value={q.focusedRetakeHint} onChange={e=>updateQuestion(qi,{focusedRetakeHint:e.target.value})} placeholder="Hint: shown only during focused retakes. Teach the idea—don’t give the answer away too easily."/><p className="muted field-help">Saved with the question. It is only displayed if a future share enables focused-retake hints. <a href="/help#focused-hints">Learn more</a></p><p className="muted">Select the circle beside the correct answer.</p>{q.choices.map((choice,ci)=><div className="choice-editor" key={ci}><input type="radio" name={`correct-${qi}`} checked={q.correctIndex===ci} onChange={()=>updateQuestion(qi,{correctIndex:ci})}/><input required value={choice} onChange={e=>updateChoice(qi,ci,e.target.value)} placeholder={`Answer choice ${ci+1}`}/><button className="ghost" type="button" onClick={()=>removeChoice(qi,ci)} disabled={q.choices.length<=2}>×</button></div>)}<button className="secondary" type="button" onClick={()=>addChoice(qi)} disabled={q.choices.length>=6}>+ Answer choice</button></section>})}<button className="secondary" type="button" onClick={addQuestion}>+ Write a new question</button></details>
  <input type="hidden" name="questions" value={payload}/><div className="row"><button type="submit" disabled={!pool.length||countInvalid}>Save test</button><span className="muted">Pool {pool.length} · Full test {pool.length?requestedCount:0}</span></div>
 </form>
}
