import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { copyTest } from './actions'

export default async function Dashboard({searchParams}:{searchParams:Promise<{error?:string}>}){
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
  const{data:profile}=await supabase.from('profiles').select('full_name,role,teacher_approved,teacher_can_invite').eq('id',user.id).single();const query=await searchParams
  if(profile?.role==='teacher'){
    if(!profile.teacher_approved)return <main className="narrow"><div className="row between"><h1>Teacher access pending</h1><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div><section className="card"><p>This account does not have approved teacher access.</p><p className="muted">Teacher tools are invite-only. Ask the approved teacher who invited you to send a valid one-time invitation link.</p></section></main>
    const{data:tests}=await supabase.from('tests').select('id,title,status,share_code,created_at,updated_at,randomize_questions,assessment_type,attempts(count)').order('updated_at',{ascending:false})
    const{count:bankCount}=await supabase.from('question_bank').select('*',{count:'exact',head:true})
    return <main>
      <div className="dashboard-heading"><div><span className="eyebrow">TEACHER WORKSPACE</span><h1>Teacher dashboard</h1><p className="muted">Welcome, {profile.full_name||user.email}</p></div><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div>
      {query.error&&<p className="bad notice">{query.error}</p>}
      <section className="card dashboard-actions">
        <div className="dashboard-primary-actions"><Link className="button dashboard-create" href="/tests/new">+ Create a test</Link></div>
        <div className="dashboard-tool-grid"><Link className="dashboard-tool" href="/question-bank"><b>Question bank</b><span>{bankCount??0} saved questions</span></Link><Link className="dashboard-tool" href="/shared-library"><b>Shared resources</b><span>Browse reusable teacher content</span></Link><Link className="dashboard-tool" href="/teacher-roster"><b>Student roster</b><span>Manage your students</span></Link><Link className="dashboard-tool" href="/teacher-groups"><b>Groups</b><span>Organize classes and cohorts</span></Link>{profile.teacher_can_invite&&<Link className="dashboard-tool" href="/teacher-access"><b>Teacher access</b><span>Invite approved teachers</span></Link>}</div>
      </section>
      <div className="row between dashboard-library-heading"><div><h2>Your test library</h2><p className="muted">Create once, then share, review, and reuse.</p></div><Link href="/tests/new">Create new →</Link></div>
      {!tests?.length?<div className="card empty-state"><h3>No tests yet</h3><p className="muted">Create your first reusable test, then share it with students when you are ready.</p><Link className="button" href="/tests/new">Create your first test</Link></div>:tests.map((t:any)=><section className="card" key={t.id}><div className="row between"><div><h3 style={{marginBottom:4}}>{t.title}</h3><p className="muted" style={{marginTop:0}}>Created {new Date(t.created_at).toLocaleDateString()} · Edited {new Date(t.updated_at).toLocaleDateString()} · {t.attempts?.[0]?.count??0} attempt(s)</p></div><span className="pill">{t.status}</span></div><p className="muted">{t.assessment_type==='psi_practice'?'PSI practice · ':''}{t.randomize_questions?'Randomized questions · ':''}Code <b className="code">{t.share_code}</b></p><div className="row" style={{flexWrap:'wrap',gap:8}}><Link className="button" href={`/tests/${t.id}`}>Share</Link><Link className="secondary button" href={`/tests/${t.id}/reports`}>Reports</Link><Link className="secondary button" href={`/tests/${t.id}/preview`}>Student view</Link><Link className="secondary button" href={`/tests/${t.id}/edit`} aria-label={`Edit ${t.title}`}>✎ Edit</Link><form action={copyTest.bind(null,t.id)}><button className="secondary" aria-label={`Copy ${t.title}`}>⧉ Copy</button></form></div></section>)}
    </main>
  }

  const[{data:attempts},{data:assignments}]=await Promise.all([
    supabase.from('attempts').select('id,test_id,share_id,score_percent,submitted_at,started_at,attempt_number,tests(title,allow_save_resume),test_shares(token)').order('started_at',{ascending:false}),
    supabase.rpc('get_my_student_assignments')
  ])
  const inProgress=(attempts??[]).filter((a:any)=>!a.submitted_at);const completed=(attempts??[]).filter((a:any)=>a.submitted_at)
  const assignmentItems=(assignments??[]) as any[]
  return <main><div className="row between"><div><h1>Student dashboard</h1><p className="muted">Welcome, {profile?.full_name||user.email}</p></div><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div>{query.error&&<p className="bad">{query.error}</p>}
    {inProgress.length>0&&<><h2>Continue where you left off</h2>{inProgress.map((a:any)=>{const share=Array.isArray(a.test_shares)?a.test_shares[0]:a.test_shares;const href=a.share_id&&share?.token?`/share/${share.token}`:`/take/${a.test_id}`;return <Link className="card card-link result-row" key={a.id} href={href}><div><b>{Array.isArray(a.tests)?a.tests[0]?.title:a.tests?.title}</b><p className="muted">Attempt {a.attempt_number} · In progress</p></div><strong>Continue →</strong></Link>})}</>}
    <div className="row between" style={{alignItems:'end',marginTop:20}}><div><h2 style={{marginBottom:4}}>My assignments</h2><p className="muted" style={{marginTop:0}}>Tests assigned directly to you or through one of your groups appear here automatically.</p></div></div>
    {!assignmentItems.length?<div className="card"><p className="muted">No active assignments yet.</p></div>:assignmentItems.map((a:any)=><Link className="card card-link" key={a.assignment_key} href={a.href}><div className="row between"><div><b>{a.assignment_label||a.title}</b>{a.assignment_label&&<p className="muted" style={{margin:'3px 0 0'}}>{a.title}</p>}</div><span className="pill">{a.access_label}</span></div><p className="muted" style={{marginBottom:4}}>{a.teacher_name}{(a.teacher_organization||a.teacher_title)?` · ${[a.teacher_organization,a.teacher_title].filter(Boolean).join(' ')}`:''}</p><p className="muted" style={{marginTop:0}}>Assigned {new Date(a.assigned_at).toLocaleString()}{a.due_at?` · Due ${new Date(a.due_at).toLocaleString()}`:' · No due date'}{a.experience_name?` · ${a.experience_name}`:''}</p></Link>)}
    <form action="/take/go" method="get" className="card"><h2>Open with a test code</h2><label>Teacher&apos;s test code</label><input name="code" required autoCapitalize="characters" placeholder="AB12CD34"/><button>Open test</button><div className="row" style={{marginTop:'1rem',flexWrap:'wrap'}}><Link className="secondary button" href="/practice-library">Browse practice passes</Link><Link className="secondary button" href="/find-teacher">Find my teacher</Link></div><p className="muted">Assigned work appears above automatically. Use Find my teacher only when you need to connect with a teacher who has not assigned anything to you yet.</p></form>
    <h2>Completed attempts</h2>{!completed.length?<div className="card"><p className="muted">You have not submitted a test yet.</p></div>:completed.map((a:any)=><Link className="card card-link result-row" key={a.id} href={`/attempts/${a.id}`}><div><b>{Array.isArray(a.tests)?a.tests[0]?.title:a.tests?.title}</b><p className="muted">Attempt {a.attempt_number} · {new Date(a.submitted_at).toLocaleString()}</p></div><strong>{a.score_percent}%</strong></Link>)}
  </main>
}
