import Link from 'next/link'
import { redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'

export default async function Dashboard({searchParams}:{searchParams:Promise<{error?:string}>}){
  const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
  const{data:profile}=await supabase.from('profiles').select('full_name,role,teacher_approved,teacher_can_invite').eq('id',user.id).single();const query=await searchParams
  if(profile?.role==='teacher'){
    if(!profile.teacher_approved)return <main className="narrow"><div className="row between"><h1>Teacher access pending</h1><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div><section className="card"><p>This account does not have approved teacher access.</p><p className="muted">Teacher tools are invite-only. Ask the approved teacher who invited you to send a valid one-time invitation link.</p></section></main>
    const{data:tests}=await supabase.from('tests').select('id,title,status,share_code,created_at,randomize_questions,assessment_type,attempts(count)').order('created_at',{ascending:false})
    const{count:bankCount}=await supabase.from('question_bank').select('*',{count:'exact',head:true})
    return <main><div className="row between"><div><h1>Teacher dashboard</h1><p className="muted">Welcome, {profile.full_name||user.email}</p></div><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div><div className="row" style={{flexWrap:'wrap'}}><Link className="button" href="/tests/new">+ Create a test</Link><Link className="secondary button" href="/psi-builder">Generate PSI practice</Link><Link className="secondary button" href="/question-bank">Question bank ({bankCount??0})</Link><Link className="secondary button" href="/shared-library">Shared resource library</Link>{profile.teacher_can_invite&&<Link className="secondary button" href="/teacher-access">Teacher access</Link>}</div><h2>Your test library</h2>{!tests?.length?<div className="card"><p className="muted">No tests yet. Create your first reusable test.</p></div>:tests.map((t:any)=><Link className="card card-link" key={t.id} href={`/tests/${t.id}`}><div className="row between"><h3>{t.title}</h3><span className="pill">{t.status}</span></div><p>Student code: <b className="code">{t.share_code}</b></p><p className="muted">{t.assessment_type==='psi_practice'?'PSI practice · ':''}{t.randomize_questions?'Randomized questions · ':''}{t.attempts?.[0]?.count??0} attempt(s)</p></Link>)}</main>
  }

  const{data:attempts}=await supabase.from('attempts').select('id,test_id,score_percent,submitted_at,started_at,attempt_number,tests(title,allow_save_resume)').order('started_at',{ascending:false})
  const{data:assignmentRows}=await supabase.from('test_assignments').select('test_id').eq('student_id',user.id)
  const assignedIds=(assignmentRows??[]).map((a:any)=>a.test_id)
  const{data:assignedTests}=assignedIds.length?await supabase.from('tests').select('id,title,due_at,available_from,status').in('id',assignedIds).eq('status','published'): {data:[] as any[]}
  const inProgress=(attempts??[]).filter((a:any)=>!a.submitted_at);const completed=(attempts??[]).filter((a:any)=>a.submitted_at)
  return <main><div className="row between"><div><h1>Student dashboard</h1><p className="muted">Welcome, {profile?.full_name||user.email}</p></div><form action="/auth/signout" method="post"><button className="ghost">Sign out</button></form></div>{query.error&&<p className="bad">{query.error}</p>}{inProgress.length>0&&<><h2>Continue where you left off</h2>{inProgress.map((a:any)=><Link className="card card-link result-row" key={a.id} href={`/take/${a.test_id}`}><div><b>{Array.isArray(a.tests)?a.tests[0]?.title:a.tests?.title}</b><p className="muted">Attempt {a.attempt_number} · In progress</p></div><strong>Continue →</strong></Link>)}</>}{(assignedTests??[]).length>0&&<><h2>Assigned tests</h2>{(assignedTests??[]).map((t:any)=><Link className="card card-link" key={t.id} href={`/take/${t.id}`}><div className="row between"><b>{t.title}</b><span className="pill">Assigned</span></div><p className="muted">{t.due_at?`Due ${new Date(t.due_at).toLocaleString()}`:'No due date'}</p></Link>)}</>}<form action="/take/go" method="get" className="card"><h2>Open with a test code</h2><label>Teacher&apos;s test code</label><input name="code" required autoCapitalize="characters" placeholder="AB12CD34"/><button>Open test</button></form><h2>Completed attempts</h2>{!completed.length?<div className="card"><p className="muted">You have not submitted a test yet.</p></div>:completed.map((a:any)=><Link className="card card-link result-row" key={a.id} href={`/attempts/${a.id}`}><div><b>{Array.isArray(a.tests)?a.tests[0]?.title:a.tests?.title}</b><p className="muted">Attempt {a.attempt_number} · {new Date(a.submitted_at).toLocaleString()}</p></div><strong>{a.score_percent}%</strong></Link>)}</main>
}
