import Link from 'next/link'
import { notFound,redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createFocusPractice } from '@/app/practice/actions'
import ShareResult from '@/components/ShareResult'

const studyTips:Record<string,string>={
'Licensing & Texas Rules':'Review current licensing requirements, exam eligibility, scope, and the official candidate information for your exam.',
'Safety, Sanitation & Infection Control':'Review cleaning vs. disinfection, single-use items, cross-contamination, blood exposure, and manufacturer contact-time directions.',
'Hair & Scalp Care':'Review hair structure, porosity, elasticity, growth cycles, scalp analysis, and service contraindications.',
'Haircutting & Styling':'Review elevation, guidelines, overdirection, weight distribution, thermal safety, and finishing techniques.',
'Chemical Texture Services':'Review disulfide bonds, permanent-wave processing, neutralization, relaxer compatibility, strand tests, and overlap safety.',
'Haircoloring & Lightening':'Review levels, tones, underlying pigment, developer, strand/patch testing, lightening safety, and color-wheel neutralization.',
'Skin Care':'Review skin analysis, epidermal layers, cleansing, exfoliation, contraindications, product selection, and facial-service safety.',
'Nail Care':'Review nail anatomy, sanitation, natural-nail filing, enhancement preparation, infection signs, and safe pedicure practices.'}
function one<T>(value:T|T[]|null|undefined):T|undefined{return Array.isArray(value)?value[0]:value??undefined}

export default async function AttemptReview({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{practice_error?:string}>}){
 const{id}=await params;const query=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const{data:attempt}=await supabase.from('attempts').select('id,student_id,score_percent,correct_count,total_questions,submitted_at,test_id,share_id,attempt_number,integrity_violation_count,focus_loss_count,fullscreen_exit_count,auto_submitted,tests(title,teacher_id,review_mode,due_at,study_guide_enabled,focused_retake_enabled,randomized_retest_enabled,passing_score_percent,questions_per_attempt,require_focused_retake_before_full,focused_retake_percent,focused_retake_min_score,focused_retake_hints),share:test_shares(token,due_at,max_attempts,unlimited_attempts_until_due,study_guide_enabled,focused_retake_enabled,randomized_retest_enabled,require_focused_retake_before_full,focused_retake_percent,focused_retake_min_score,focused_retake_hints),student:profiles!attempts_student_id_fkey(full_name),responses(id,is_correct,choice_id,question_id,questions(prompt,position,content_area,choices(id,label,position))),attempt_integrity_events(event_type,created_at)').eq('id',id).single();if(!attempt)notFound()
 const test=one(attempt.tests),share=one(attempt.share),student=one(attempt.student);const isStudent=attempt.student_id===user.id,isTeacher=test?.teacher_id===user.id;if(!isStudent&&!isTeacher)notFound()
 const assignmentDue=share?.due_at??test?.due_at;const duePassed=Boolean(assignmentDue)&&Date.now()>=new Date(assignmentDue as string).getTime();const reviewAllowed=isTeacher||test?.review_mode==='immediate'||(test?.review_mode==='after_due'&&duePassed)
 const{data:lockedRows}=await supabase.from('attempt_questions').select('question_id,position').eq('attempt_id',id).order('position')
 const attemptPosition=new Map((lockedRows??[]).map((r:any)=>[String(r.question_id),Number(r.position)]))
 const responses=[...(attempt.responses??[])].sort((a:any,b:any)=>(attemptPosition.get(String(a.question_id))??9999)-(attemptPosition.get(String(b.question_id))??9999));const events=[...(attempt.attempt_integrity_events??[])].sort((a:any,b:any)=>String(a.created_at).localeCompare(String(b.created_at)))
 const passing=Number(test?.passing_score_percent??70),failed=Number(attempt.score_percent??0)<passing
 const guideEnabled=share?.study_guide_enabled??test?.study_guide_enabled??true
 const requiredFocused=Boolean(share?share.require_focused_retake_before_full:test?.require_focused_retake_before_full)
 const focusedEnabled=requiredFocused||(share?.focused_retake_enabled??test?.focused_retake_enabled??true)
 const randomizedEnabled=share?.randomized_retest_enabled??test?.randomized_retest_enabled??true
 const focusedPercent=Number(share?.focused_retake_percent??test?.focused_retake_percent??50),focusedMinScore=Number(share?.focused_retake_min_score??test?.focused_retake_min_score??0),focusedHints=Boolean(share?.focused_retake_hints??test?.focused_retake_hints)
 const focusedCount=Math.max(1,Math.ceil(Number(test?.questions_per_attempt??attempt.total_questions??1)*focusedPercent/100))
 const areaMap=new Map<string,{total:number;missed:number}>();for(const r of responses){const q=one(r.questions as any),area=q?.content_area||'General review',row=areaMap.get(area)||{total:0,missed:0};row.total++;if(!r.is_correct)row.missed++;areaMap.set(area,row)}
 const allAreas=[...areaMap.entries()].sort((a,b)=>b[1].missed-a[1].missed),focus=allAreas.filter(([,v])=>v.missed>0),focusAreas=focus.map(([a])=>a).slice(0,3)
 const{data:focusedSessions}=isStudent&&requiredFocused?await supabase.from('practice_sessions').select('score_percent,status').eq('source_attempt_id',id).eq('student_id',user.id).eq('status','submitted'):{data:[] as any[]}
 const focusedGateMet=!requiredFocused||(focusedSessions??[]).some((s:any)=>Number(s.score_percent??0)>=focusedMinScore)
 const{data:recommended}=focusAreas.length?await supabase.from('shared_collections').select('id,title,description,subject,collection_type,shared_collection_questions(count)').eq('active',true).eq('student_available',true).eq('catalog_scope','platform').in('title',focusAreas.map(a=>`${a} Practice Set`)):{data:[] as any[]}
 const freshHref=share?.token?`/share/${share.token}?fresh=1`:`/take/${attempt.test_id}?fresh=1`
 return <main><Link href={isStudent?'/dashboard':`/tests/${attempt.test_id}`}>← Back</Link><h1>{test?.title}</h1><section className="score-card"><span className="score">{attempt.score_percent}%</span><div><b>{attempt.correct_count} of {attempt.total_questions} correct</b><p className="muted">{student?.full_name||'Student'} · Attempt {attempt.attempt_number}</p></div></section>
 {isStudent&&attempt.submitted_at&&<ShareResult score={Number(attempt.score_percent??0)} title={test?.title||'practice test'} passingScore={passing}/>} 
 {isStudent&&attempt.submitted_at&&(guideEnabled||focusedEnabled||randomizedEnabled)&&<section className="card"><h2>What should I do next?</h2><p className="muted">Use the weak-area step to improve what cost you points, then take another full readiness test when your assignment&apos;s retake rules allow it.</p><div className="grid two">
  {failed&&guideEnabled&&<a className="card card-link" href="#study-guide"><b>Study what I missed</b><p className="muted">Review the subjects and concepts that cost you points.</p></a>}
  {failed&&focusedEnabled&&<a className="card card-link" href="#focused-retake"><b>{requiredFocused?'Required focused retest':'Retake weak areas'}</b><p className="muted">{requiredFocused?`${focusedCount} questions · ${focusedPercent}% of the full test · ${focusedMinScore===0?'completion required':`${focusedMinScore}% required`}.`:'Build a focused randomized mini-test from the subjects that need improvement.'}</p></a>}
  {randomizedEnabled&&(!failed||focusedGateMet)?<Link className="card card-link" href={freshHref}><b>Take a new randomized full test</b><p className="muted">Start another allowed attempt with a fresh subject-balanced question set.</p></Link>:failed&&requiredFocused&&randomizedEnabled?<div className="card"><b>Full retest locked</b><p className="muted">Complete the required focused retest{focusedMinScore>0?` with at least ${focusedMinScore}%`:''} first.</p></div>:null}
 </div></section>}
 {failed&&guideEnabled&&<section className="card" id="study-guide"><h2>Your study guide</h2><p>You scored below the {passing}% target. Start with the areas where you lost the most points.</p>{focus.map(([area,v])=><div className="question-summary" key={area}><b>{area}</b><p>Missed {v.missed} of {v.total} question{v.total===1?'':'s'}.</p><p className="muted">{studyTips[area]||`Review the core concepts, vocabulary, rules, and procedures for ${area}.`}</p></div>)}
 {isStudent&&focusedEnabled&&<form id="focused-retake" action={createFocusPractice.bind(null,id)} className="card stack"><h3>{requiredFocused?'Required focused retest':'Retake weak areas'}</h3>{query.practice_error&&<p className="bad">{query.practice_error}</p>}{requiredFocused?<><p className="muted">This assignment sets focused retests to {focusedPercent}% of the full test, so this retest will use about <b>{focusedCount} questions</b>, concentrated first on the areas you missed.</p>{focus.map(([area,v])=><p key={area}><b>{area}</b> <span className="muted">· {v.missed} missed</span></p>)}<input type="hidden" name="question_count" value={focusedCount}/>{focus.map(([area])=><input key={area} type="hidden" name="areas" value={area}/>) }<p className="muted">Unlock requirement: {focusedMinScore===0?'complete the focused retest':`score at least ${focusedMinScore}%`}.{focusedHints?' Learning hints are enabled.':''}</p></>:<><p className="muted">Missed areas start checked. Add or remove topics before creating the randomized retake.</p>{allAreas.map(([area,v])=><label className="check" key={area}><input type="checkbox" name="areas" value={area} defaultChecked={v.missed>0}/><span><b>{area}</b> <span className="muted">· {v.missed>0?`${v.missed} missed`:'extra review'}</span></span></label>)}<label>Retake size</label><select name="question_count" defaultValue="10"><option value="5">5 questions</option><option value="10">10 questions</option><option value="15">15 questions</option><option value="20">20 questions</option></select></>}<button>Create focused retest</button></form>}
 {(recommended??[]).length>0&&<><h3>Related practice resources</h3>{(recommended??[]).map((r:any)=><Link className="card card-link" key={r.id} href={`/practice-library?resource=${r.id}`}><div className="row between"><div><b>{r.title}</b><p className="muted">{r.shared_collection_questions?.[0]?.count??0} focused questions</p></div><strong>View →</strong></div></Link>)}</>}</section>}
 {isTeacher&&<section className="card"><h2>Testing integrity</h2><p><b>{attempt.integrity_violation_count}</b> event(s) recorded · {attempt.focus_loss_count} focus loss · {attempt.fullscreen_exit_count} fullscreen exit</p>{events.map((e:any)=><p className="muted" key={`${e.event_type}-${e.created_at}`}>{new Date(e.created_at).toLocaleTimeString()} — {String(e.event_type).replaceAll('_',' ')}</p>)}</section>}
 {!reviewAllowed?<section className="card"><h2>Answer review is not available yet</h2></section>:<><h2>Review</h2>{responses.map((r:any,index:number)=>{const q=one(r.questions as any),choices=q?.choices??[],selected=choices.find((c:any)=>c.id===r.choice_id);return <section className={`card review ${r.is_correct?'correct':'incorrect'}`} key={r.id}><div className="row between"><b>{index+1}. {q?.prompt}</b><span className={r.is_correct?'good':'bad'}>{r.is_correct?'Correct':'Incorrect'}</span></div><p>Your answer: <b>{selected?.label||'No answer'}</b></p></section>})}</>}
 </main>}
