create extension if not exists pgcrypto;

create type public.user_role as enum ('teacher','student');
create type public.test_status as enum ('draft','published','archived');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade,full_name text,role public.user_role not null default 'student',created_at timestamptz not null default now());
create table public.tests (id uuid primary key default gen_random_uuid(),teacher_id uuid not null references public.profiles(id) on delete cascade,title text not null,description text,status public.test_status not null default 'draft',share_code text not null unique default upper(substr(replace(gen_random_uuid()::text,'-',''),1,8)),randomize_questions boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.questions (id uuid primary key default gen_random_uuid(),test_id uuid not null references public.tests(id) on delete cascade,prompt text not null,position integer not null check (position > 0),created_at timestamptz not null default now(),unique(test_id, position));
create table public.choices (id uuid primary key default gen_random_uuid(),question_id uuid not null references public.questions(id) on delete cascade,label text not null,position integer not null check (position > 0),unique(question_id, position));
create table public.question_answers (question_id uuid primary key references public.questions(id) on delete cascade,choice_id uuid not null references public.choices(id) on delete cascade);
create table public.attempts (id uuid primary key default gen_random_uuid(),test_id uuid not null references public.tests(id) on delete cascade,student_id uuid not null references public.profiles(id) on delete cascade,started_at timestamptz not null default now(),submitted_at timestamptz,correct_count integer not null default 0,total_questions integer not null default 0,score_percent numeric(5,2) not null default 0);
create table public.responses (id uuid primary key default gen_random_uuid(),attempt_id uuid not null references public.attempts(id) on delete cascade,question_id uuid not null references public.questions(id) on delete cascade,choice_id uuid references public.choices(id) on delete set null,is_correct boolean not null default false,unique(attempt_id, question_id));

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = '' as $$ begin insert into public.profiles(id, full_name, role) values(new.id,nullif(trim(new.raw_user_meta_data->>'full_name'), ''),case when new.raw_user_meta_data->>'requested_role' = 'teacher' then 'teacher'::public.user_role else 'student'::public.user_role end);return new;end;$$;
revoke all on function public.handle_new_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.create_test_with_questions(p_title text,p_description text,p_randomize boolean,p_questions jsonb) returns uuid language plpgsql security definer set search_path = '' as $$ declare v_user uuid := auth.uid();v_test uuid;v_question uuid;v_choice uuid;v_correct_choice uuid;q jsonb;c jsonb;q_index int := 0;c_index int;correct_index int; begin if v_user is null then raise exception 'Authentication required'; end if;if not exists (select 1 from public.profiles p where p.id=v_user and p.role='teacher') then raise exception 'Teacher account required'; end if;if nullif(trim(p_title), '') is null then raise exception 'Title is required'; end if;if jsonb_typeof(p_questions) <> 'array' or jsonb_array_length(p_questions) = 0 then raise exception 'At least one question is required'; end if;insert into public.tests(teacher_id,title,description,randomize_questions) values(v_user, trim(p_title), nullif(trim(p_description), ''), coalesce(p_randomize,false)) returning id into v_test;for q in select value from jsonb_array_elements(p_questions) loop q_index := q_index + 1;if nullif(trim(q->>'prompt'), '') is null then raise exception 'Question % needs a prompt', q_index; end if;if jsonb_typeof(q->'choices') <> 'array' or jsonb_array_length(q->'choices') < 2 then raise exception 'Question % needs at least two choices', q_index; end if;correct_index := coalesce((q->>'correctIndex')::int, -1);if correct_index < 0 or correct_index >= jsonb_array_length(q->'choices') then raise exception 'Question % needs a correct answer', q_index; end if;insert into public.questions(test_id,prompt,position) values(v_test, trim(q->>'prompt'), q_index) returning id into v_question;c_index := 0;v_correct_choice := null;for c in select value from jsonb_array_elements(q->'choices') loop if nullif(trim(c#>>'{}'), '') is null then raise exception 'Question % contains an empty choice', q_index; end if;insert into public.choices(question_id,label,position) values(v_question, trim(c#>>'{}'), c_index + 1) returning id into v_choice;if c_index = correct_index then v_correct_choice := v_choice; end if;c_index := c_index + 1;end loop;insert into public.question_answers(question_id,choice_id) values(v_question,v_correct_choice);end loop;return v_test;end;$$;
revoke all on function public.create_test_with_questions(text,text,boolean,jsonb) from public, anon;grant execute on function public.create_test_with_questions(text,text,boolean,jsonb) to authenticated;

create or replace function public.submit_test_attempt(p_test_id uuid, p_answers jsonb) returns uuid language plpgsql security definer set search_path = '' as $$ declare v_user uuid := auth.uid();v_attempt uuid;v_total int;v_correct int;q record;v_choice uuid; begin if v_user is null then raise exception 'Authentication required'; end if;if not exists (select 1 from public.tests t where t.id=p_test_id and t.status='published') then raise exception 'Test unavailable'; end if;if not exists (select 1 from public.profiles p where p.id=v_user and p.role='student') then raise exception 'Student account required'; end if;insert into public.attempts(test_id,student_id) values(p_test_id,v_user) returning id into v_attempt;for q in select id from public.questions where test_id=p_test_id loop begin v_choice := nullif(p_answers->>q.id::text,'')::uuid; exception when invalid_text_representation then v_choice := null; end;if v_choice is not null and not exists (select 1 from public.choices c where c.id=v_choice and c.question_id=q.id) then v_choice := null; end if;insert into public.responses(attempt_id,question_id,choice_id,is_correct) values(v_attempt,q.id,v_choice,exists(select 1 from public.question_answers a where a.question_id=q.id and a.choice_id=v_choice));end loop;select count(*), count(*) filter(where is_correct) into v_total,v_correct from public.responses where attempt_id=v_attempt;update public.attempts set submitted_at=now(),total_questions=v_total,correct_count=v_correct,score_percent=case when v_total=0 then 0 else round((v_correct::numeric/v_total)*100,2) end where id=v_attempt;return v_attempt;end;$$;
revoke all on function public.submit_test_attempt(uuid,jsonb) from public, anon;grant execute on function public.submit_test_attempt(uuid,jsonb) to authenticated;

alter table public.profiles enable row level security;alter table public.tests enable row level security;alter table public.questions enable row level security;alter table public.choices enable row level security;alter table public.question_answers enable row level security;alter table public.attempts enable row level security;alter table public.responses enable row level security;
grant select on public.profiles to authenticated;grant select,insert,update,delete on public.tests,public.questions,public.choices,public.question_answers to authenticated;grant select on public.attempts,public.responses to authenticated;
create policy profiles_self on public.profiles for select to authenticated using ((select auth.uid())=id);
create policy profiles_teacher_attempt_students on public.profiles for select to authenticated using (exists(select 1 from public.attempts a join public.tests t on t.id=a.test_id where a.student_id=profiles.id and t.teacher_id=(select auth.uid())));
create policy teachers_own_tests_select on public.tests for select to authenticated using (teacher_id=(select auth.uid()) or status='published');
create policy teachers_own_tests_insert on public.tests for insert to authenticated with check (teacher_id=(select auth.uid()) and exists(select 1 from public.profiles p where p.id=(select auth.uid()) and p.role='teacher'));
create policy teachers_own_tests_update on public.tests for update to authenticated using (teacher_id=(select auth.uid())) with check (teacher_id=(select auth.uid()));
create policy teachers_own_tests_delete on public.tests for delete to authenticated using (teacher_id=(select auth.uid()));
create policy questions_read on public.questions for select to authenticated using (exists(select 1 from public.tests t where t.id=test_id and (t.teacher_id=(select auth.uid()) or t.status='published')));
create policy questions_teacher_write on public.questions for all to authenticated using (exists(select 1 from public.tests t where t.id=test_id and t.teacher_id=(select auth.uid()))) with check (exists(select 1 from public.tests t where t.id=test_id and t.teacher_id=(select auth.uid())));
create policy choices_read on public.choices for select to authenticated using (exists(select 1 from public.questions q join public.tests t on t.id=q.test_id where q.id=question_id and (t.teacher_id=(select auth.uid()) or t.status='published')));
create policy choices_teacher_write on public.choices for all to authenticated using (exists(select 1 from public.questions q join public.tests t on t.id=q.test_id where q.id=question_id and t.teacher_id=(select auth.uid()))) with check (exists(select 1 from public.questions q join public.tests t on t.id=q.test_id where q.id=question_id and t.teacher_id=(select auth.uid())));
create policy answers_teacher_only on public.question_answers for all to authenticated using (exists(select 1 from public.questions q join public.tests t on t.id=q.test_id where q.id=question_id and t.teacher_id=(select auth.uid()))) with check (exists(select 1 from public.questions q join public.tests t on t.id=q.test_id where q.id=question_id and t.teacher_id=(select auth.uid())));
create policy attempts_owner_or_teacher on public.attempts for select to authenticated using (student_id=(select auth.uid()) or exists(select 1 from public.tests t where t.id=test_id and t.teacher_id=(select auth.uid())));
create policy responses_owner_or_teacher on public.responses for select to authenticated using (exists(select 1 from public.attempts a join public.tests t on t.id=a.test_id where a.id=attempt_id and (a.student_id=(select auth.uid()) or t.teacher_id=(select auth.uid()))));
create index tests_teacher_idx on public.tests(teacher_id);create index tests_share_code_idx on public.tests(share_code);create index questions_test_idx on public.questions(test_id);create index attempts_test_idx on public.attempts(test_id);create index attempts_student_idx on public.attempts(student_id);create index responses_attempt_idx on public.responses(attempt_id);
