import Link from 'next/link'

export const metadata={title:'Help & FAQs | CramLoop'}

const faqs=[
  {id:'focused-hints',q:'What are focused-retake hints?',a:<><p>Focused-retake hints are short teaching cues attached to individual questions. They are designed to remind a student what concept, rule, process, or safety principle to think through without giving away the answer.</p><p>Hints appear only during a focused retake when the teacher has enabled hints. They do not appear on the original full test or a normal full retest.</p></>},
  {id:'write-hint',q:'How should I write a good hint?',a:<><p>Point the student toward the reasoning process rather than the correct choice. A useful hint might tell the student to compare two concepts, remember the correct sequence, identify the safest procedure, or think about the rule that applies.</p><p><b>Avoid:</b> repeating the answer, naming the correct choice, or narrowing the options so far that no reasoning is required.</p></>},
  {id:'focused-retests',q:'How do required focused retests work?',a:<><p>A teacher can require a shorter weak-area retest after a failed full attempt. The teacher controls the focused-retest size as a percentage of the full-test question count and can set a minimum focused score required before another full attempt unlocks.</p><p>A 0% requirement means the student only needs to complete the focused retest before proceeding.</p></>},
  {id:'question-pools',q:'Why can the question pool be larger than the test?',a:<><p>The teacher-selected pool defines which questions CramLoop is allowed to use. The full-test question count can be smaller than that pool, allowing later attempts to draw a different subject-balanced set while staying within the material the teacher approved.</p></>},
  {id:'due-dates',q:'What happens at the due date?',a:<><p>After the due date and time, no new full attempt or focused retest can begin. Completed attempts and grades remain available to the teacher in reporting. If a timed attempt begins close to the due date, the overall due time still acts as the final deadline.</p></>},
  {id:'shared-hints',q:'Can I edit a hint copied from the Shared Library?',a:<><p>Yes. Shared-library questions are copied into the teacher’s personal question bank. The copied hint can then be edited or removed without changing CramLoop’s shared or Verified source question.</p></>},
  {id:'verified-content',q:'What does CramLoop Verified mean?',a:<><p>CramLoop Verified means CramLoop has intentionally reviewed the resource for its stated exam, skill, or subject goal and tracks its content version and review date. It does not mean a regulator, testing vendor, school, or licensing board has endorsed the resource unless CramLoop explicitly says so.</p><p>Verified practice questions are original study material and are not represented as proprietary or actual exam questions.</p></>},
]

export default function HelpPage(){return <main className="narrow"><Link href="/dashboard">← Back</Link><h1>Help & FAQs</h1><p className="muted">Short answers for building tests, retakes, hints, and CramLoop content.</p><div className="stack">{faqs.map(f=><details className="card" id={f.id} key={f.id}><summary><b>{f.q}</b></summary><div style={{paddingTop:10}}>{f.a}</div></details>)}</div><section className="card"><h2>More FAQs are being prepared</h2><p className="muted">We’re still expanding help for sharing, reports, student access, integrity settings, teacher-created resources, billing, and account management. Product controls may change as those workflows are completed.</p></section><p className="muted">For platform rules and legal information, see <Link href="/terms">Terms</Link>, <Link href="/privacy">Privacy</Link>, <Link href="/acceptable-use">Acceptable Use</Link>, and <Link href="/content-disclaimer">Content & Exam Disclaimer</Link>.</p></main>}
