import Link from 'next/link'
import { notFound,redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createShareOffer,saveDeliveryControls,setShareActive,setTestStatus } from './actions'

function localInput(value:string|null){if(!value)return'';const d=new Date(value);const pad=(n:number)=>String(n).padStart(2,'0');return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`}
type StudentSummaryRow={name:string;best:number;attempts:any[]}

export default async function TestDetail({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string}>}){
 const{id}=await params;const query=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const{data:profile}=await supabase.from('profiles').select('teacher_plan,teacher_plan_expires_at').eq('id',user.id).single();const proActive=profile?.teacher_plan==='pro'&&(!profile.teacher_plan_expires_at||new Date(profile.teacher_plan_expires_at).getTime()>Date.now())
 const{data:test}=await supabase.from('tests').select('id,title,description,status,share_code,randomize_questions,randomize_choices,teacher_id,assignment_mode,max_attempts,allow_save_resume,study_guide_enabled,focused_retake_enabled,randomized_retest_enabled,strict_mode,integrity_action,integrity_limit,review_mode,available_from,due_at,questions(id,prompt,position,choices(id,label,position)),attempts(id,share_id,score_percent,correct_count,total_questions,submitted_at,student_id,attempt_number,integrity_violation_count,focus_loss_count,fullscreen_exit_count,auto_submitted,student:profiles!attempts_student_id_fkey(full_name))').eq('id',id).single();if(!test||test.teacher_id!==user.id)notFound()
 const[{data:students},{data:assigned},{data:roster},{data:groups},{data:shares}]=await Promise.all([
  supabase.from('profiles').select('id,full_name').eq('role','student').order('full_name'),
  supabase.from('test_assignments').select('student_id').eq('test_id',id),
  supabase.from('teacher_student_roster').select('id,student_email,student_id').eq('teacher_id',user.id).order('student_email'),
  supabase.from('teacher_groups').select('id,name,teacher_group_members(count)').eq('teacher_id',user.id).order('name'),
  supabase.from('test_shares').select('id,token,label,delivery_mode,restricted_mode,audience_mode,access_mode,payment_mode,max_attempts,access_duration_days,study_guide_enabled,focused_retake_enabled,randomized_retest_enabled,link_expires_at,price_cents,teacher_revenue_share_bps,active,created_at').eq('test_id',id).order('created_at',{ascending:false})
 ])
 const assignedIds=new Set((assigned??[]).map((a:any)=>a.student_id));const questions=[...(test.questions??[])].sort((a:any,b:any)=>a.position-b.position);const attempts=[...(test.attempts??[])].sort((a:any,b:any)=>String(b.submitted_at).localeCompare(String(a.submitted_at)));const completed=attempts.filter((a:any)=>a.submitted_at)
 const studentSummary=new Map<string,StudentSummaryRow>();for(const a of completed){const student=Array.isArray(a.student)?a.student[0]:a.student;const key=String(a.student_id);const row=studentSummary.get(key)??{name:student?.full_name||'Student',best:0,attempts:[]};row.best=Math.max(row.best,Number(a.score_percent||0));row.attempts.push(a);studentSummary.set(key,row)}
 const legacyUrl=`https://cramloop.app/take/${id}`
 return <main><Link href="/dashboard">← Dashboard</Link><div className="row between"><div><h1>{test.title}</h1><p className="muted">{test.description||'No description'}</p></div><span className="pill">{test.status}</span></div>{query.error&&<p className="bad">{query.error}</p>}
  <section className="card"><h2>Publish</h2><p>Legacy classroom code: <b className="code">{test.share_code}</b></p><p><a href={legacyUrl}>{legacyUrl}</a></p><p className="muted">Share links below can give this same test different rules, audiences, and post-test learning options without rebuilding it.</p><p>Question order: <b>{test.randomize_questions?'Randomized':'Fixed'}</b></p><form action={setTestStatus.bind(null,id,test.status==='published'?'draft':'published')}><button>{test.status==='published'?'Unpublish test':'Publish test'}</button></form></section>

  <section className="card stack"><div><h2>Share this test</h2><p className="muted">Choose the testing experience, audience, and what students can do after they submit.</p></div><form action={createShareOffer.bind(null,id)} className="stack">
   <label>Share label</label><input name="label" placeholder="Week 1 exam, study retake, 14-day pass"/>
   <label>How should students use this share?</label><select name="delivery_mode" defaultValue="standard"><option value="standard">Standard test — 1–5 attempts</option><option value="restricted">Restricted Test Mode — 1–5 attempts + integrity monitoring</option><option value="study">Study mode — test + study guide + weak-area retake</option><option value="paid_pass">Paid practice access — Pro only + unlimited attempts</option></select>
   <div className="card"><h3>After the test</h3><label className="check"><input type="checkbox" name="study_guide_enabled"/><b>Study guide</b> — show the subjects and concepts that need improvement</label><label className="check"><input type="checkbox" name="focused_retake_enabled"/><b>Weak-area retake</b> — let students build a randomized retake from missed subjects</label><label className="check"><input type="checkbox" name="randomized_retest_enabled" defaultChecked/><b>Fresh randomized test</b> — let students use another allowed attempt with question and answer order reshuffled</label><p className="muted">Study mode automatically enables the study guide and weak-area retake. Paid practice access enables all three.</p></div>
   <label>Who should receive this share?</label><select name="audience_mode" defaultValue="link"><option value="link">Anyone with this share link</option><option value="students">Specific students from my roster</option><option value="groups">Specific roster groups</option></select>
   <div className="settings-grid"><div><h3>Roster students</h3>{!(roster??[]).length?<p className="muted">No roster students yet.</p>:(roster??[]).map((r:any)=><label className="check" key={r.id}><input type="checkbox" name="roster_ids" value={r.id}/>{r.student_email}{r.student_id?'':' · not signed up yet'}</label>)}<Link href="/teacher-roster">Manage student roster →</Link></div><div><h3>Groups</h3>{!(groups??[]).length?<p className="muted">No groups yet.</p>:(groups??[]).map((g:any)=><label className="check" key={g.id}><input type="checkbox" name="group_ids" value={g.id}/>{g.name} ({g.teacher_group_members?.[0]?.count??0})</label>)}<Link href="/teacher-groups">Manage groups →</Link></div></div>
   <div className="settings-grid"><div><label>Attempts</label><input name="max_attempts" type="number" min="1" max="5" defaultValue="1"/><p className="muted">Fresh randomized retests still count toward this limit. Paid passes use unlimited attempts.</p></div><div><label>Optional link expiration</label><input name="link_expires_at" type="datetime-local"/></div></div>
   <div className="settings-grid"><div><label>Paid pass length</label><input name="access_duration_days" type="number" min="1" max="365" defaultValue="14"/></div><div><label>Paid pass price</label><input name="price_dollars" type="number" min="1" step="0.01" placeholder="12.99"/><p className="muted">{proActive?'Your account can create paid access.':'Teacher Pro is only required when charging students.'}</p></div></div><button>Create share link</button>
  </form></section>

  {(shares??[]).length>0&&<section className="card"><h2>Share links</h2>{(shares??[]).map((s:any)=>{const url=`https://cramloop.app/share/${s.token}`;const mode=s.delivery_mode==='paid_pass'?'Paid access':s.delivery_mode==='study'?'Study mode':s.delivery_mode==='restricted'?'Restricted test':'Standard test';const audience=s.audience_mode==='students'?'Selected students':s.audience_mode==='groups'?'Selected groups':'Anyone with link';return <div className="question-summary" key={s.id}><div className="row between"><div><b>{s.label||'Untitled share'}</b><p><a href={url}>{url}</a></p><p className="muted">{mode} · {audience} · {s.max_attempts==null?'Unlimited attempts':`${s.max_attempts} attempt${s.max_attempts===1?'':'s'}`} · Guide {s.study_guide_enabled?'on':'off'} · Weak-area retake {s.focused_retake_enabled?'on':'off'} · Fresh randomized test {s.randomized_retest_enabled?'on':'off'}{s.restricted_mode?' · Integrity monitoring on':''}{s.payment_mode==='paid'?` · $${((s.price_cents||0)/100).toFixed(2)} · ${s.access_duration_days||14}-day access`:''}</p></div><span className="pill">{s.active?'Active':'Disabled'}</span></div><form action={setShareActive.bind(null,id,s.id,!s.active)}><button className="secondary">{s.active?'Disable link':'Enable link'}</button></form></div>})}</section>}

  <form action={saveDeliveryControls.bind(null,id)} className="card stack"><h2>Classroom access & test controls</h2><label>Who can take this test?</label><select name="assignment_mode" defaultValue={test.assignment_mode}><option value="link">Anyone with the code/link</option><option value="assigned">Only assigned students</option></select><label>Assign students</label><div className="stack">{!students?.length?<p className="muted">Student accounts will appear here after they sign up.</p>:students.map((s:any)=><label className="check" key={s.id}><input type="checkbox" name="student_ids" value={s.id} defaultChecked={assignedIds.has(s.id)}/>{s.full_name||'Student'}</label>)}</div>
   <div className="settings-grid"><div><label>Attempts allowed</label><input name="max_attempts" type="number" min="1" max="20" defaultValue={test.max_attempts}/></div><div><label>Review answers</label><select name="review_mode" defaultValue={test.review_mode}><option value="immediate">Immediately after submission</option><option value="after_due">After due date</option><option value="never">Score only — no answer review</option></select></div></div>
   <div className="settings-grid"><div><label>Available from</label><input name="available_from" type="datetime-local" defaultValue={localInput(test.available_from)}/></div><div><label>Due / closes</label><input name="due_at" type="datetime-local" defaultValue={localInput(test.due_at)}/></div></div>
   <h3>Post-test learning loop</h3><label className="check"><input name="study_guide_enabled" type="checkbox" defaultChecked={test.study_guide_enabled}/><b>Study guide after a failed attempt</b></label><label className="check"><input name="focused_retake_enabled" type="checkbox" defaultChecked={test.focused_retake_enabled}/><b>Allow weak-area randomized retakes</b></label><label className="check"><input name="randomized_retest_enabled" type="checkbox" defaultChecked={test.randomized_retest_enabled}/><b>Allow fresh randomized retests</b></label><p className="muted">A fresh randomized retest uses another normal allowed attempt; it does not bypass your attempt limit.</p>
   <label className="check"><input name="allow_save_resume" type="checkbox" defaultChecked={test.allow_save_resume}/>Allow students to save and resume an in-progress attempt</label><label className="check"><input name="randomize_choices" type="checkbox" defaultChecked={test.randomize_choices}/>Randomize answer-choice order on normal attempts</label><hr/><label className="check"><input name="strict_mode" type="checkbox" defaultChecked={test.strict_mode}/><b>Strict Test Mode</b> — fullscreen plus tab/app, copy/paste, right-click and fullscreen-exit monitoring</label><div className="settings-grid"><div><label>When an integrity event occurs</label><select name="integrity_action" defaultValue={test.integrity_action}><option value="flag">Record it silently</option><option value="warn">Record it and warn the student</option><option value="auto_submit">Auto-submit after the limit</option></select></div><div><label>Auto-submit violation limit</label><input name="integrity_limit" type="number" min="1" max="20" defaultValue={test.integrity_limit}/></div></div><button>Save test controls</button></form>

  <section className="card"><h2>Questions ({questions.length})</h2>{questions.map((q:any)=><div className="question-summary" key={q.id}><b>{q.position}. {q.prompt}</b><p className="muted">{q.choices?.length??0} choices</p></div>)}</section>
  <section className="card"><h2>Student results ({completed.length} completed)</h2>{studentSummary.size===0?<p className="muted">No completed attempts yet.</p>:[...studentSummary.entries()].map(([studentId,row])=><div className="question-summary" key={studentId}><div className="row between"><div><b>{row.name}</b><p className="muted">{row.attempts.length} completed attempt{row.attempts.length===1?'':'s'}</p></div><div><b>Highest grade: {row.best}%</b></div></div>{row.attempts.sort((a:any,b:any)=>a.attempt_number-b.attempt_number).map((a:any)=><div className="result-row" key={a.id}><div><b>Attempt {a.attempt_number}</b><p className="muted">{new Date(a.submitted_at).toLocaleString()}{a.auto_submitted?' · Auto-submitted':''}</p></div><div><b>{a.score_percent}%</b><p className="muted">{a.correct_count}/{a.total_questions} correct · {a.integrity_violation_count} integrity event(s)</p></div><Link href={`/attempts/${a.id}`}>Attempt details</Link></div>)}</div>)}</section>
 </main>
}
