import Link from 'next/link'
import { notFound,redirect } from 'next/navigation'
import { createClient } from '@/lib/supabase/server'
import { createShareOffer,setShareActive,setTestStatus } from './actions'
import AudiencePicker from './AudiencePicker'

type StudentSummaryRow={name:string;best:number;attempts:any[]}

export default async function TestDetail({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{error?:string}>}){
 const{id}=await params;const query=await searchParams;const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)redirect('/login')
 const{data:profile}=await supabase.from('profiles').select('teacher_plan,teacher_plan_expires_at').eq('id',user.id).single();const proActive=profile?.teacher_plan==='pro'&&(!profile.teacher_plan_expires_at||new Date(profile.teacher_plan_expires_at).getTime()>Date.now())
 const{data:test}=await supabase.from('tests').select('id,title,description,status,share_code,randomize_questions,teacher_id,questions_per_attempt,questions(id,prompt,position,choices(id,label,position)),attempts(id,share_id,score_percent,correct_count,total_questions,submitted_at,student_id,attempt_number,integrity_violation_count,focus_loss_count,fullscreen_exit_count,auto_submitted,student:profiles!attempts_student_id_fkey(full_name))').eq('id',id).single();if(!test||test.teacher_id!==user.id)notFound()
 const[{data:roster},{data:groups},{data:shares}]=await Promise.all([
  supabase.from('teacher_student_roster').select('id,student_email,student_id').eq('teacher_id',user.id).order('student_email'),
  supabase.from('teacher_groups').select('id,name,teacher_group_members(count)').eq('teacher_id',user.id).order('name'),
  supabase.from('test_shares').select('id,token,label,delivery_mode,restricted_mode,audience_mode,access_mode,payment_mode,max_attempts,unlimited_attempts_until_due,due_at,require_focused_retake_before_full,focused_retake_percent,focused_retake_min_score,focused_retake_hints,access_duration_days,study_guide_enabled,focused_retake_enabled,randomized_retest_enabled,link_expires_at,price_cents,teacher_revenue_share_bps,active,created_at').eq('test_id',id).order('created_at',{ascending:false})
 ])
 const questions=[...(test.questions??[])].sort((a:any,b:any)=>a.position-b.position);const attempts=[...(test.attempts??[])].sort((a:any,b:any)=>String(b.submitted_at).localeCompare(String(a.submitted_at)));const completed=attempts.filter((a:any)=>a.submitted_at)
 const studentSummary=new Map<string,StudentSummaryRow>();for(const a of completed){const student=Array.isArray(a.student)?a.student[0]:a.student;const key=String(a.student_id);const existing=studentSummary.get(key);const row:StudentSummaryRow=existing??{name:student?.full_name||'Student',best:0,attempts:[] as any[]};row.best=Math.max(row.best,Number(a.score_percent||0));row.attempts.push(a as any);studentSummary.set(key,row)}
 const audienceGroups=(groups??[]).map((g:any)=>({id:g.id,name:g.name,member_count:g.teacher_group_members?.[0]?.count??0}))
 const audienceRoster=(roster??[]).map((r:any)=>({id:r.id,student_email:r.student_email,student_id:r.student_id??null}))
 return <main><Link href="/dashboard">← Dashboard</Link><div className="row between"><div><h1>{test.title}</h1><p className="muted">{test.description||'No summary'}</p></div><span className="pill">{test.status}</span></div>{query.error&&<p className="bad">{query.error}</p>}

  <section className="card"><div className="row between"><div><h2>Reusable test</h2><p className="muted">{questions.length} questions in pool · {test.questions_per_attempt||questions.length} shown per full test. Deadlines and retake rules are set separately for each share.</p></div><form action={setTestStatus.bind(null,id,test.status==='published'?'draft':'published')}><button>{test.status==='published'?'Unpublish test':'Publish test'}</button></form></div><p>Question order: <b>{test.randomize_questions?'Randomized':'Fixed'}</b></p></section>

  <section className="card stack"><div><h2>Share this test</h2><p className="muted">This creates an assignment using the reusable test above. Each share can have its own students, deadline, attempt limit, and retake requirements.</p></div><form action={createShareOffer.bind(null,id)} className="stack">
   <label>Assignment / share label <span className="muted">(optional)</span></label><input name="label" placeholder="Period 2 final, Week 1 exam, makeup assignment"/>
   <label>Testing experience</label><select name="delivery_mode" defaultValue="standard"><option value="standard">Standard test</option><option value="restricted">Restricted Test Mode + integrity monitoring</option><option value="study">Study mode + study guide + weak-area retake</option><option value="paid_pass">Paid practice access — Pro only</option></select>

   <section className="notice"><h3>Deadline & full retakes</h3><div className="settings-grid"><div><label>Full test attempts</label><input name="max_attempts" type="number" min="1" max="100" defaultValue="2"/><p className="muted">Example: 2 attempts means the original attempt plus 1 full retake.</p></div><div><label>Due date & time</label><input name="due_at" type="datetime-local"/><p className="muted">Optional with limited attempts. Required if unlimited attempts are enabled.</p></div></div><label className="check"><input type="checkbox" name="unlimited_attempts_until_due"/><span><b>Unlimited full retakes until due date</b> — ignore the attempt count above and allow full retakes until the assignment closes.</span></label></section>

   <section className="notice"><h3>After a failed full attempt</h3><label className="check"><input type="checkbox" name="require_focused_retake_before_full"/><span><b>Require a focused retest before another full retake</b></span></label><div className="settings-grid"><div><label>Focused retest size</label><select name="focused_retake_percent" defaultValue="50">{[10,20,30,40,50,60,70,80,90,100].map(n=><option key={n} value={n}>{n}% of full test</option>)}</select><p className="muted">For a {test.questions_per_attempt||questions.length}-question full test, 50% is about {Math.max(1,Math.ceil((test.questions_per_attempt||questions.length)*.5))} focused questions.</p></div><div><label>Grade required to proceed</label><select name="focused_retake_min_score" defaultValue="0">{Array.from({length:101},(_,n)=><option key={n} value={n}>{n}%{n===0?' · completion only':''}</option>)}</select><p className="muted">0% means completing the focused retest unlocks the next full attempt regardless of score.</p></div></div><label className="check"><input type="checkbox" name="focused_retake_hints" defaultChecked/><span><b>Show per-question teaching hints on focused retests</b> — hints never appear on the full test. <a href="/help#focused-hints">Learn more</a></span></label></section>

   <section className="notice"><h3>After-test learning <span className="muted">(optional)</span></h3><label className="check"><input type="checkbox" name="study_guide_enabled"/><b>Study guide</b> — show subjects and concepts that need improvement</label><label className="check"><input type="checkbox" name="focused_retake_enabled"/><b>Allow optional weak-area retakes</b> — available even when not required as a gate</label><label className="check"><input type="checkbox" name="randomized_retest_enabled" defaultChecked/><b>Fresh randomized full retest</b> — uses another allowed full attempt</label><p className="muted">Requiring a focused retest automatically enables the focused-retake path for that share.</p></section>

   <AudiencePicker roster={audienceRoster} groups={audienceGroups}/>
   <label>Share-link expiration <span className="muted">(optional)</span></label><input name="link_expires_at" type="datetime-local"/><p className="muted">This can disable the link itself earlier than the assignment due date. Usually the due date is enough.</p>
   <details className="card"><summary><b>Paid practice access settings</b></summary><div className="settings-grid"><div><label>Access length</label><input name="access_duration_days" type="number" min="1" max="365" defaultValue="14"/></div><div><label>Price</label><input name="price_dollars" type="number" min="1" step="0.01" placeholder="12.99"/></div></div><p className="muted">{proActive?'Your account can create paid access.':'Teacher Pro is only required when charging students.'}</p></details>
   <button>Create share link</button>
  </form></section>

  {(shares??[]).length>0&&<section className="card"><h2>Share links / assignments</h2>{(shares??[]).map((s:any)=>{const url=`https://cramloop.app/share/${s.token}`;const mode=s.delivery_mode==='paid_pass'?'Paid access':s.delivery_mode==='study'?'Study mode':s.delivery_mode==='restricted'?'Restricted test':'Standard test';const audience=s.audience_mode==='students'?'Selected students':s.audience_mode==='groups'?'Selected groups':'Anyone with link';const attemptsLabel=s.payment_mode==='paid'?'Practice access':s.unlimited_attempts_until_due?'Unlimited until due date':`${s.max_attempts||1} full attempt${(s.max_attempts||1)===1?'':'s'}`;const focusLabel=s.require_focused_retake_before_full?`Focused retest required · ${s.focused_retake_percent}% size · ${s.focused_retake_min_score}% to proceed`:(s.focused_retake_enabled?'Focused retest optional':'No focused retest');return <div className="question-summary" key={s.id}><div className="row between"><div><b>{s.label||'Untitled share'}</b><p><a href={url}>{url}</a></p><p className="muted">{mode} · {audience} · {attemptsLabel}{s.due_at?` · Due ${new Date(s.due_at).toLocaleString()}`:' · No due date'} · {focusLabel}{s.focused_retake_hints?' · Hints on focused retest':''}{s.restricted_mode?' · Integrity monitoring on':''}{s.payment_mode==='paid'?` · $${((s.price_cents||0)/100).toFixed(2)} · ${s.access_duration_days||14}-day access`:''}</p></div><span className="pill">{s.active?'Active':'Disabled'}</span></div><form action={setShareActive.bind(null,id,s.id,!s.active)}><button className="secondary">{s.active?'Disable link':'Enable link'}</button></form></div>})}</section>}

  <section className="card"><h2>Questions ({questions.length})</h2>{questions.map((q:any)=><div className="question-summary" key={q.id}><b>{q.position}. {q.prompt}</b><p className="muted">{q.choices?.length??0} choices</p></div>)}</section>
  <section className="card"><h2>Student results ({completed.length} completed)</h2><p className="muted">Completed grades remain in reporting even after an assignment reaches its due date.</p>{studentSummary.size===0?<p className="muted">No completed attempts yet.</p>:[...studentSummary.entries()].map(([studentId,row])=><div className="question-summary" key={studentId}><div className="row between"><div><b>{row.name}</b><p className="muted">{row.attempts.length} completed attempt{row.attempts.length===1?'':'s'}</p></div><div><b>Highest grade: {row.best}%</b></div></div>{row.attempts.sort((a:any,b:any)=>a.attempt_number-b.attempt_number).map((a:any)=><div className="result-row" key={a.id}><div><b>Attempt {a.attempt_number}</b><p className="muted">{new Date(a.submitted_at).toLocaleString()}{a.auto_submitted?' · Auto-submitted':''}</p></div><div><b>{a.score_percent}%</b><p className="muted">{a.correct_count}/{a.total_questions} correct · {a.integrity_violation_count} integrity event(s)</p></div><Link href={`/attempts/${a.id}`}>Attempt details</Link></div>)}</div>)}</section>
 </main>
}
