'use client'

import {useMemo,useState} from 'react'

type QuestionMeta={chapter_number:number|null;chapter_title:string|null;subject_category:string|null;content_area:string|null}
type Blueprint={id?:string;name?:string;description?:string|null;chapter_filters?:Array<{chapter_number:number|null;chapter_title:string}>;subject_weights?:Record<string,number>;question_count?:number;duration_minutes?:number;passing_score_percent?:number;randomize_questions?:boolean;one_question_per_page?:boolean}

function chapterKey(q:{chapter_number?:number|null;chapter_title?:string|null}){return q.chapter_number?`n:${q.chapter_number}|${q.chapter_title||''}`:q.chapter_title?`t:${q.chapter_title}`:'none'}
function chapterText(q:{chapter_number?:number|null;chapter_title?:string|null}){if(q.chapter_number)return `Chapter ${q.chapter_number}${q.chapter_title?` — ${q.chapter_title}`:''}`;return q.chapter_title||'No chapter'}
function subjectOf(q:QuestionMeta){return (q.subject_category||q.content_area||'General / untagged').trim()}

export default function BlueprintEditor({action,questions,initial}:{action:(formData:FormData)=>void;questions:QuestionMeta[];initial?:Blueprint}){
  const chapterMap=useMemo(()=>{const map=new Map<string,{chapter_number:number|null;chapter_title:string;label:string}>();for(const q of questions){const key=chapterKey(q);if(key==='none')continue;map.set(key,{chapter_number:q.chapter_number??null,chapter_title:q.chapter_title||'',label:chapterText(q)})}return map},[questions])
  const chapterOptions=useMemo(()=>[...chapterMap.entries()].sort((a,b)=>a[1].label.localeCompare(b[1].label,undefined,{numeric:true})),[chapterMap])
  const initialKeys=useMemo(()=>new Set((initial?.chapter_filters||[]).map(f=>f.chapter_number?`n:${f.chapter_number}|${f.chapter_title||''}`:f.chapter_title?`t:${f.chapter_title}`:'none').filter(k=>k!=='none')),[initial])
  const[selected,setSelected]=useState<Set<string>>(initialKeys)
  const[weights,setWeights]=useState<Record<string,string>>(()=>Object.fromEntries(Object.entries(initial?.subject_weights||{}).map(([k,v])=>[k,String(v)])))
  const relevantQuestions=useMemo(()=>questions.filter(q=>selected.size===0||selected.has(chapterKey(q))),[questions,selected])
  const subjects=useMemo(()=>[...new Set(relevantQuestions.map(subjectOf))].sort(),[relevantQuestions])
  const total=subjects.reduce((sum,s)=>sum+(Number(weights[s])||0),0)
  const hasWeights=subjects.some(s=>(Number(weights[s])||0)>0)
  const chapterFilters=[...selected].map(key=>chapterMap.get(key)).filter(Boolean).map(x=>({chapter_number:x!.chapter_number,chapter_title:x!.chapter_title}))
  const subjectWeights=Object.fromEntries(subjects.map(s=>[s,Number(weights[s])||0]).filter(([,v])=>v>0))
  function toggle(key:string){setSelected(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);return next})}
  function equalize(){if(!subjects.length)return;const base=Math.floor(100/subjects.length);let remainder=100-base*subjects.length;const next:Record<string,string>={};for(const s of subjects)next[s]=String(base+(remainder-->0?1:0));setWeights(next)}

  return <form action={action} className="stack">
    {initial?.id&&<input type="hidden" name="id" value={initial.id}/>}<input type="hidden" name="chapter_filters" value={JSON.stringify(chapterFilters)}/><input type="hidden" name="subject_weights" value={JSON.stringify(subjectWeights)}/>
    <section className="card"><h2>{initial?.id?'Edit blueprint':'New smart-test blueprint'}</h2><p className="muted">Save the recipe, not a fixed test. Each generation pulls a fresh set from your current question bank.</p><label>Blueprint name</label><input name="name" required defaultValue={initial?.name||''} placeholder="Example: Chapter 6 Final Review"/><label>Description <span className="muted">(optional)</span></label><textarea name="description" rows={2} defaultValue={initial?.description||''}/><div className="settings-grid"><div><label>Questions</label><input name="question_count" type="number" min="1" max="200" defaultValue={initial?.question_count??40}/></div><div><label>Timer (minutes)</label><input name="duration_minutes" type="number" min="0" max="600" defaultValue={initial?.duration_minutes??45}/></div><div><label>Passing score (%)</label><input name="passing_score_percent" type="number" min="0" max="100" defaultValue={initial?.passing_score_percent??70}/></div></div><label className="check"><input name="randomize_questions" type="checkbox" defaultChecked={initial?.randomize_questions??true}/> Randomize generated question order</label><label className="check"><input name="one_question_per_page" type="checkbox" defaultChecked={initial?.one_question_per_page??true}/> One question per page</label></section>
    <section className="card"><div className="row between"><div><h2>Chapter filter</h2><p className="muted">Choose one or several chapters. Leave every chapter unchecked to pull from the whole bank.</p></div><span className="pill">{selected.size?`${selected.size} selected`:'All chapters'}</span></div>{chapterOptions.length?<div className="blueprint-chapters">{chapterOptions.map(([key,item])=><label className="check blueprint-check" key={key}><input type="checkbox" checked={selected.has(key)} onChange={()=>toggle(key)}/><span><b>{item.label}</b><small>{questions.filter(q=>chapterKey(q)===key).length} questions</small></span></label>)}</div>:<p className="muted">No chapter metadata yet. Organize questions in the Question Bank first, or save this as an all-bank blueprint.</p>}</section>
    <section className="card"><div className="row between"><div><h2>Subject mix</h2><p className="muted">Set exact percentages or leave all percentages blank/zero for an automatic balanced mix.</p></div><button type="button" className="secondary" onClick={equalize}>Balance evenly</button></div>{subjects.length?<div className="blueprint-subjects">{subjects.map(subject=><label key={subject}><span>{subject}</span><div className="weight-input"><input type="number" min="0" max="100" value={weights[subject]||''} onChange={e=>setWeights(current=>({...current,[subject]:e.target.value}))} placeholder="0"/><b>%</b></div></label>)}</div>:<p className="muted">No subject categories match the selected chapters yet.</p>}<p className={hasWeights&&Math.round(total)!==100?'bad':'muted'}>{hasWeights?`Configured total: ${total}%${Math.round(total)===100?' ✓':' — must equal 100%'}`:'No custom weights — CramLoop will balance available subjects automatically.'}</p></section>
    <button type="submit" disabled={hasWeights&&Math.round(total)!==100}>{initial?.id?'Save changes':'Save blueprint'}</button>
    <style jsx global>{`.blueprint-chapters{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:8px}.blueprint-check{padding:10px 12px;border:1px solid #e4e7ef;border-radius:10px;background:#fff}.blueprint-check span{display:block}.blueprint-check small{display:block;color:#64748b;margin-top:2px}.blueprint-subjects{display:grid;gap:8px}.blueprint-subjects>label{display:grid;grid-template-columns:1fr 120px;gap:12px;align-items:center;padding:8px 0;border-bottom:1px solid #eef0f4}.weight-input{display:flex;align-items:center;gap:6px}.weight-input input{margin:0}.weight-input b{font-size:12px;color:#64748b}@media(max-width:640px){.blueprint-subjects>label{grid-template-columns:1fr 100px}}`}</style>
  </form>
}
